/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Rainbow Frontend Gateway API
 * OpenAPI specification for the Rainbow Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorInfo,
  OdrlPolicyDto
} from '.././model';

import { customInstance } from '../../orval-mutator';
import type { ErrorType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get ODRL policies by entity ID
 */
export type getPoliciesByEntityIdResponse200 = {
  data: OdrlPolicyDto[]
  status: 200
}

export type getPoliciesByEntityIdResponse400 = {
  data: ErrorInfo
  status: 400
}

export type getPoliciesByEntityIdResponse401 = {
  data: ErrorInfo
  status: 401
}

export type getPoliciesByEntityIdResponse403 = {
  data: ErrorInfo
  status: 403
}

export type getPoliciesByEntityIdResponse404 = {
  data: ErrorInfo
  status: 404
}

export type getPoliciesByEntityIdResponse500 = {
  data: ErrorInfo
  status: 500
}
    
export type getPoliciesByEntityIdResponseSuccess = (getPoliciesByEntityIdResponse200) & {
  headers: Headers;
};
export type getPoliciesByEntityIdResponseError = (getPoliciesByEntityIdResponse400 | getPoliciesByEntityIdResponse401 | getPoliciesByEntityIdResponse403 | getPoliciesByEntityIdResponse404 | getPoliciesByEntityIdResponse500) & {
  headers: Headers;
};

export type getPoliciesByEntityIdResponse = (getPoliciesByEntityIdResponseSuccess | getPoliciesByEntityIdResponseError)

export const getGetPoliciesByEntityIdUrl = (entityId: string,) => {


  

  return `/odrl-policies/entity/${entityId}`
}

export const getPoliciesByEntityId = async (entityId: string, options?: RequestInit): Promise<getPoliciesByEntityIdResponse> => {
  
  return customInstance<getPoliciesByEntityIdResponse>(getGetPoliciesByEntityIdUrl(entityId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPoliciesByEntityIdInfiniteQueryKey = (entityId: string,) => {
    return [
    'infinite', `/odrl-policies/entity/${entityId}`
    ] as const;
    }

export const getGetPoliciesByEntityIdQueryKey = (entityId: string,) => {
    return [
    `/odrl-policies/entity/${entityId}`
    ] as const;
    }

    
export const getGetPoliciesByEntityIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getPoliciesByEntityId>>>, TError = ErrorType<ErrorInfo>>(entityId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPoliciesByEntityId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPoliciesByEntityIdInfiniteQueryKey(entityId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPoliciesByEntityId>>> = ({ signal }) => getPoliciesByEntityId(entityId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(entityId),  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPoliciesByEntityId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPoliciesByEntityIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getPoliciesByEntityId>>>
export type GetPoliciesByEntityIdInfiniteQueryError = ErrorType<ErrorInfo>


export function useGetPoliciesByEntityIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPoliciesByEntityId>>>, TError = ErrorType<ErrorInfo>>(
 entityId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPoliciesByEntityId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPoliciesByEntityId>>,
          TError,
          Awaited<ReturnType<typeof getPoliciesByEntityId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPoliciesByEntityIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPoliciesByEntityId>>>, TError = ErrorType<ErrorInfo>>(
 entityId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPoliciesByEntityId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPoliciesByEntityId>>,
          TError,
          Awaited<ReturnType<typeof getPoliciesByEntityId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPoliciesByEntityIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPoliciesByEntityId>>>, TError = ErrorType<ErrorInfo>>(
 entityId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPoliciesByEntityId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get ODRL policies by entity ID
 */

export function useGetPoliciesByEntityIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPoliciesByEntityId>>>, TError = ErrorType<ErrorInfo>>(
 entityId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPoliciesByEntityId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPoliciesByEntityIdInfiniteQueryOptions(entityId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetPoliciesByEntityIdQueryOptions = <TData = Awaited<ReturnType<typeof getPoliciesByEntityId>>, TError = ErrorType<ErrorInfo>>(entityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPoliciesByEntityId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPoliciesByEntityIdQueryKey(entityId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPoliciesByEntityId>>> = ({ signal }) => getPoliciesByEntityId(entityId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(entityId),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPoliciesByEntityId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPoliciesByEntityIdQueryResult = NonNullable<Awaited<ReturnType<typeof getPoliciesByEntityId>>>
export type GetPoliciesByEntityIdQueryError = ErrorType<ErrorInfo>


export function useGetPoliciesByEntityId<TData = Awaited<ReturnType<typeof getPoliciesByEntityId>>, TError = ErrorType<ErrorInfo>>(
 entityId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPoliciesByEntityId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPoliciesByEntityId>>,
          TError,
          Awaited<ReturnType<typeof getPoliciesByEntityId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPoliciesByEntityId<TData = Awaited<ReturnType<typeof getPoliciesByEntityId>>, TError = ErrorType<ErrorInfo>>(
 entityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPoliciesByEntityId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPoliciesByEntityId>>,
          TError,
          Awaited<ReturnType<typeof getPoliciesByEntityId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPoliciesByEntityId<TData = Awaited<ReturnType<typeof getPoliciesByEntityId>>, TError = ErrorType<ErrorInfo>>(
 entityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPoliciesByEntityId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get ODRL policies by entity ID
 */

export function useGetPoliciesByEntityId<TData = Awaited<ReturnType<typeof getPoliciesByEntityId>>, TError = ErrorType<ErrorInfo>>(
 entityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPoliciesByEntityId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPoliciesByEntityIdQueryOptions(entityId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




