version: "3"
services:

  db-consumer:
    container_name: db-consumer
    image: "postgres"
    restart: always
    ports:
      - "5439:5432"
    environment:
      POSTGRES_PASSWORD: ds_core_consumer_db
      POSTGRES_USER: ds_core_consumer_db
      POSTGRES_DB: ds_core_consumer_db

  ds-consumer:
    container_name: ds-consumer
    image: caparicioesd/rainbow
    restart: on-failure
    depends_on:
      - db-consumer
    ports:
      - "1235:1235"
    env_file:
      - "./.env.consumer.template"
    command: [ "consumer", "start" ]

  ds-consumer-setup:
    container_name: ds-consumer-setup
    image: caparicioesd/rainbow
    restart: on-failure
    depends_on:
      - db-consumer
    env_file:
      - "./.env.consumer.template"
    command: [ "consumer", "setup" ]
networks:
  ds-rainbow:
    external: true
