# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema.provider]
file = "./src/transfer/provider/data/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
filter = { only_tables = ["transfer_message_fields", "transfer_messages", "transfer_processes"] }


[print_schema.consumer]
file = "./src/transfer/consumer/data/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
filter = { only_tables = ["transfer_callbacks"] }


[migrations_directory]
dir = "./src/db/migrations"
