/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * OpenAPI specification for the Eunomia DS-Agent Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  CreateUserCommand,
  InternalServerErrorResponse,
  JwksResponse,
  OAuthRevokeRequest,
  OAuthTokenRequest,
  OAuthTokenResponse,
  OAuthUser,
  OAuthUserInfo,
  TokenIntrospectionResponse
} from '.././model';

import { customInstance } from '../../orval-mutator';
import type { ErrorType , BodyType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Exchange client credentials, authorization code + PKCE, refresh token, or RFC 7523 JWT Profile for an access token
 * @summary Issue OAuth 2.0 access token
 */
export type createOAuthTokenWithJsonResponse200 = {
  data: OAuthTokenResponse
  status: 200
}

export type createOAuthTokenWithJsonResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createOAuthTokenWithJsonResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type createOAuthTokenWithJsonResponseSuccess = (createOAuthTokenWithJsonResponse200) & {
  headers: Headers;
};
export type createOAuthTokenWithJsonResponseError = (createOAuthTokenWithJsonResponse400 | createOAuthTokenWithJsonResponse500) & {
  headers: Headers;
};

export type createOAuthTokenWithJsonResponse = (createOAuthTokenWithJsonResponseSuccess | createOAuthTokenWithJsonResponseError)

export const getCreateOAuthTokenWithJsonUrl = () => {


  

  return `/oauth/token`
}

export const createOAuthTokenWithJson = async (oAuthTokenRequest: OAuthTokenRequest, options?: RequestInit): Promise<createOAuthTokenWithJsonResponse> => {
  
  return customInstance<createOAuthTokenWithJsonResponse>(getCreateOAuthTokenWithJsonUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oAuthTokenRequest,)
  }
);}




export const getCreateOAuthTokenWithJsonMutationOptions = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOAuthTokenWithJson>>, TError,{data: BodyType<OAuthTokenRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createOAuthTokenWithJson>>, TError,{data: BodyType<OAuthTokenRequest>}, TContext> => {

const mutationKey = ['createOAuthTokenWithJson'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOAuthTokenWithJson>>, {data: BodyType<OAuthTokenRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createOAuthTokenWithJson(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOAuthTokenWithJsonMutationResult = NonNullable<Awaited<ReturnType<typeof createOAuthTokenWithJson>>>
    export type CreateOAuthTokenWithJsonMutationBody = BodyType<OAuthTokenRequest>
    export type CreateOAuthTokenWithJsonMutationError = ErrorType<BadRequestResponse | InternalServerErrorResponse>

    /**
 * @summary Issue OAuth 2.0 access token
 */
export const useCreateOAuthTokenWithJson = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOAuthTokenWithJson>>, TError,{data: BodyType<OAuthTokenRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOAuthTokenWithJson>>,
        TError,
        {data: BodyType<OAuthTokenRequest>},
        TContext
      > => {
      return useMutation(getCreateOAuthTokenWithJsonMutationOptions(options), queryClient);
    }
    /**
 * Exchange client credentials, authorization code + PKCE, refresh token, or RFC 7523 JWT Profile for an access token
 * @summary Issue OAuth 2.0 access token
 */
export type createOAuthTokenWithUrlEncodedResponse200 = {
  data: OAuthTokenResponse
  status: 200
}

export type createOAuthTokenWithUrlEncodedResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createOAuthTokenWithUrlEncodedResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type createOAuthTokenWithUrlEncodedResponseSuccess = (createOAuthTokenWithUrlEncodedResponse200) & {
  headers: Headers;
};
export type createOAuthTokenWithUrlEncodedResponseError = (createOAuthTokenWithUrlEncodedResponse400 | createOAuthTokenWithUrlEncodedResponse500) & {
  headers: Headers;
};

export type createOAuthTokenWithUrlEncodedResponse = (createOAuthTokenWithUrlEncodedResponseSuccess | createOAuthTokenWithUrlEncodedResponseError)

export const getCreateOAuthTokenWithUrlEncodedUrl = () => {


  

  return `/oauth/token`
}

export const createOAuthTokenWithUrlEncoded = async ( options?: RequestInit): Promise<createOAuthTokenWithUrlEncodedResponse> => {
  
  return customInstance<createOAuthTokenWithUrlEncodedResponse>(getCreateOAuthTokenWithUrlEncodedUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getCreateOAuthTokenWithUrlEncodedMutationOptions = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOAuthTokenWithUrlEncoded>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createOAuthTokenWithUrlEncoded>>, TError,void, TContext> => {

const mutationKey = ['createOAuthTokenWithUrlEncoded'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOAuthTokenWithUrlEncoded>>, void> = () => {
          

          return  createOAuthTokenWithUrlEncoded(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOAuthTokenWithUrlEncodedMutationResult = NonNullable<Awaited<ReturnType<typeof createOAuthTokenWithUrlEncoded>>>
    
    export type CreateOAuthTokenWithUrlEncodedMutationError = ErrorType<BadRequestResponse | InternalServerErrorResponse>

    /**
 * @summary Issue OAuth 2.0 access token
 */
export const useCreateOAuthTokenWithUrlEncoded = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOAuthTokenWithUrlEncoded>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOAuthTokenWithUrlEncoded>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getCreateOAuthTokenWithUrlEncodedMutationOptions(options), queryClient);
    }
    /**
 * RFC 7009 token revocation
 * @summary Revoke access or refresh token
 */
export type revokeOAuthTokenResponse200 = {
  data: void
  status: 200
}

export type revokeOAuthTokenResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type revokeOAuthTokenResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type revokeOAuthTokenResponseSuccess = (revokeOAuthTokenResponse200) & {
  headers: Headers;
};
export type revokeOAuthTokenResponseError = (revokeOAuthTokenResponse400 | revokeOAuthTokenResponse500) & {
  headers: Headers;
};

export type revokeOAuthTokenResponse = (revokeOAuthTokenResponseSuccess | revokeOAuthTokenResponseError)

export const getRevokeOAuthTokenUrl = () => {


  

  return `/oauth/revoke`
}

export const revokeOAuthToken = async (oAuthRevokeRequest: OAuthRevokeRequest, options?: RequestInit): Promise<revokeOAuthTokenResponse> => {
  
  return customInstance<revokeOAuthTokenResponse>(getRevokeOAuthTokenUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oAuthRevokeRequest,)
  }
);}




export const getRevokeOAuthTokenMutationOptions = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeOAuthToken>>, TError,{data: BodyType<OAuthRevokeRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof revokeOAuthToken>>, TError,{data: BodyType<OAuthRevokeRequest>}, TContext> => {

const mutationKey = ['revokeOAuthToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeOAuthToken>>, {data: BodyType<OAuthRevokeRequest>}> = (props) => {
          const {data} = props ?? {};

          return  revokeOAuthToken(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RevokeOAuthTokenMutationResult = NonNullable<Awaited<ReturnType<typeof revokeOAuthToken>>>
    export type RevokeOAuthTokenMutationBody = BodyType<OAuthRevokeRequest>
    export type RevokeOAuthTokenMutationError = ErrorType<BadRequestResponse | InternalServerErrorResponse>

    /**
 * @summary Revoke access or refresh token
 */
export const useRevokeOAuthToken = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeOAuthToken>>, TError,{data: BodyType<OAuthRevokeRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revokeOAuthToken>>,
        TError,
        {data: BodyType<OAuthRevokeRequest>},
        TContext
      > => {
      return useMutation(getRevokeOAuthTokenMutationOptions(options), queryClient);
    }
    /**
 * RFC 7662 token introspection
 * @summary Introspect token
 */
export type introspectOAuthTokenResponse200 = {
  data: TokenIntrospectionResponse
  status: 200
}

export type introspectOAuthTokenResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type introspectOAuthTokenResponseSuccess = (introspectOAuthTokenResponse200) & {
  headers: Headers;
};
export type introspectOAuthTokenResponseError = (introspectOAuthTokenResponse500) & {
  headers: Headers;
};

export type introspectOAuthTokenResponse = (introspectOAuthTokenResponseSuccess | introspectOAuthTokenResponseError)

export const getIntrospectOAuthTokenUrl = () => {


  

  return `/oauth/introspect`
}

export const introspectOAuthToken = async (oAuthRevokeRequest: OAuthRevokeRequest, options?: RequestInit): Promise<introspectOAuthTokenResponse> => {
  
  return customInstance<introspectOAuthTokenResponse>(getIntrospectOAuthTokenUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oAuthRevokeRequest,)
  }
);}




export const getIntrospectOAuthTokenMutationOptions = <TError = ErrorType<InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof introspectOAuthToken>>, TError,{data: BodyType<OAuthRevokeRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof introspectOAuthToken>>, TError,{data: BodyType<OAuthRevokeRequest>}, TContext> => {

const mutationKey = ['introspectOAuthToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof introspectOAuthToken>>, {data: BodyType<OAuthRevokeRequest>}> = (props) => {
          const {data} = props ?? {};

          return  introspectOAuthToken(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type IntrospectOAuthTokenMutationResult = NonNullable<Awaited<ReturnType<typeof introspectOAuthToken>>>
    export type IntrospectOAuthTokenMutationBody = BodyType<OAuthRevokeRequest>
    export type IntrospectOAuthTokenMutationError = ErrorType<InternalServerErrorResponse>

    /**
 * @summary Introspect token
 */
export const useIntrospectOAuthToken = <TError = ErrorType<InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof introspectOAuthToken>>, TError,{data: BodyType<OAuthRevokeRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof introspectOAuthToken>>,
        TError,
        {data: BodyType<OAuthRevokeRequest>},
        TContext
      > => {
      return useMutation(getIntrospectOAuthTokenMutationOptions(options), queryClient);
    }
    /**
 * OpenID Connect UserInfo endpoint
 * @summary Get user info
 */
export type getOAuthUserInfoResponse200 = {
  data: OAuthUserInfo
  status: 200
}

export type getOAuthUserInfoResponse401 = {
  data: BadRequestResponse
  status: 401
}

export type getOAuthUserInfoResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type getOAuthUserInfoResponseSuccess = (getOAuthUserInfoResponse200) & {
  headers: Headers;
};
export type getOAuthUserInfoResponseError = (getOAuthUserInfoResponse401 | getOAuthUserInfoResponse500) & {
  headers: Headers;
};

export type getOAuthUserInfoResponse = (getOAuthUserInfoResponseSuccess | getOAuthUserInfoResponseError)

export const getGetOAuthUserInfoUrl = () => {


  

  return `/oauth/userinfo`
}

export const getOAuthUserInfo = async ( options?: RequestInit): Promise<getOAuthUserInfoResponse> => {
  
  return customInstance<getOAuthUserInfoResponse>(getGetOAuthUserInfoUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetOAuthUserInfoInfiniteQueryKey = () => {
    return [
    'infinite', `/oauth/userinfo`
    ] as const;
    }

export const getGetOAuthUserInfoQueryKey = () => {
    return [
    `/oauth/userinfo`
    ] as const;
    }

    
export const getGetOAuthUserInfoInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getOAuthUserInfo>>>, TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthUserInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOAuthUserInfoInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOAuthUserInfo>>> = ({ signal }) => getOAuthUserInfo({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthUserInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetOAuthUserInfoInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getOAuthUserInfo>>>
export type GetOAuthUserInfoInfiniteQueryError = ErrorType<BadRequestResponse | InternalServerErrorResponse>


export function useGetOAuthUserInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getOAuthUserInfo>>>, TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthUserInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOAuthUserInfo>>,
          TError,
          Awaited<ReturnType<typeof getOAuthUserInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetOAuthUserInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getOAuthUserInfo>>>, TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthUserInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOAuthUserInfo>>,
          TError,
          Awaited<ReturnType<typeof getOAuthUserInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetOAuthUserInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getOAuthUserInfo>>>, TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthUserInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get user info
 */

export function useGetOAuthUserInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getOAuthUserInfo>>>, TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthUserInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetOAuthUserInfoInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetOAuthUserInfoQueryOptions = <TData = Awaited<ReturnType<typeof getOAuthUserInfo>>, TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuthUserInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOAuthUserInfoQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOAuthUserInfo>>> = ({ signal }) => getOAuthUserInfo({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOAuthUserInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetOAuthUserInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getOAuthUserInfo>>>
export type GetOAuthUserInfoQueryError = ErrorType<BadRequestResponse | InternalServerErrorResponse>


export function useGetOAuthUserInfo<TData = Awaited<ReturnType<typeof getOAuthUserInfo>>, TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuthUserInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOAuthUserInfo>>,
          TError,
          Awaited<ReturnType<typeof getOAuthUserInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetOAuthUserInfo<TData = Awaited<ReturnType<typeof getOAuthUserInfo>>, TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuthUserInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOAuthUserInfo>>,
          TError,
          Awaited<ReturnType<typeof getOAuthUserInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetOAuthUserInfo<TData = Awaited<ReturnType<typeof getOAuthUserInfo>>, TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuthUserInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get user info
 */

export function useGetOAuthUserInfo<TData = Awaited<ReturnType<typeof getOAuthUserInfo>>, TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuthUserInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetOAuthUserInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get JSON Web Key Set
 */
export type getOAuthJwksResponse200 = {
  data: JwksResponse
  status: 200
}

export type getOAuthJwksResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type getOAuthJwksResponseSuccess = (getOAuthJwksResponse200) & {
  headers: Headers;
};
export type getOAuthJwksResponseError = (getOAuthJwksResponse500) & {
  headers: Headers;
};

export type getOAuthJwksResponse = (getOAuthJwksResponseSuccess | getOAuthJwksResponseError)

export const getGetOAuthJwksUrl = () => {


  

  return `/oauth/.well-known/jwks.json`
}

export const getOAuthJwks = async ( options?: RequestInit): Promise<getOAuthJwksResponse> => {
  
  return customInstance<getOAuthJwksResponse>(getGetOAuthJwksUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetOAuthJwksInfiniteQueryKey = () => {
    return [
    'infinite', `/oauth/.well-known/jwks.json`
    ] as const;
    }

export const getGetOAuthJwksQueryKey = () => {
    return [
    `/oauth/.well-known/jwks.json`
    ] as const;
    }

    
export const getGetOAuthJwksInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getOAuthJwks>>>, TError = ErrorType<InternalServerErrorResponse>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthJwks>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOAuthJwksInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOAuthJwks>>> = ({ signal }) => getOAuthJwks({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthJwks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetOAuthJwksInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getOAuthJwks>>>
export type GetOAuthJwksInfiniteQueryError = ErrorType<InternalServerErrorResponse>


export function useGetOAuthJwksInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getOAuthJwks>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthJwks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOAuthJwks>>,
          TError,
          Awaited<ReturnType<typeof getOAuthJwks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetOAuthJwksInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getOAuthJwks>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthJwks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOAuthJwks>>,
          TError,
          Awaited<ReturnType<typeof getOAuthJwks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetOAuthJwksInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getOAuthJwks>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthJwks>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get JSON Web Key Set
 */

export function useGetOAuthJwksInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getOAuthJwks>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthJwks>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetOAuthJwksInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetOAuthJwksQueryOptions = <TData = Awaited<ReturnType<typeof getOAuthJwks>>, TError = ErrorType<InternalServerErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuthJwks>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOAuthJwksQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOAuthJwks>>> = ({ signal }) => getOAuthJwks({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOAuthJwks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetOAuthJwksQueryResult = NonNullable<Awaited<ReturnType<typeof getOAuthJwks>>>
export type GetOAuthJwksQueryError = ErrorType<InternalServerErrorResponse>


export function useGetOAuthJwks<TData = Awaited<ReturnType<typeof getOAuthJwks>>, TError = ErrorType<InternalServerErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuthJwks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOAuthJwks>>,
          TError,
          Awaited<ReturnType<typeof getOAuthJwks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetOAuthJwks<TData = Awaited<ReturnType<typeof getOAuthJwks>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuthJwks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOAuthJwks>>,
          TError,
          Awaited<ReturnType<typeof getOAuthJwks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetOAuthJwks<TData = Awaited<ReturnType<typeof getOAuthJwks>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuthJwks>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get JSON Web Key Set
 */

export function useGetOAuthJwks<TData = Awaited<ReturnType<typeof getOAuthJwks>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuthJwks>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetOAuthJwksQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List users
 */
export type listOAuthUsersResponse200 = {
  data: OAuthUser[]
  status: 200
}

export type listOAuthUsersResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type listOAuthUsersResponseSuccess = (listOAuthUsersResponse200) & {
  headers: Headers;
};
export type listOAuthUsersResponseError = (listOAuthUsersResponse500) & {
  headers: Headers;
};

export type listOAuthUsersResponse = (listOAuthUsersResponseSuccess | listOAuthUsersResponseError)

export const getListOAuthUsersUrl = () => {


  

  return `/oauth/users`
}

export const listOAuthUsers = async ( options?: RequestInit): Promise<listOAuthUsersResponse> => {
  
  return customInstance<listOAuthUsersResponse>(getListOAuthUsersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListOAuthUsersInfiniteQueryKey = () => {
    return [
    'infinite', `/oauth/users`
    ] as const;
    }

export const getListOAuthUsersQueryKey = () => {
    return [
    `/oauth/users`
    ] as const;
    }

    
export const getListOAuthUsersInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof listOAuthUsers>>>, TError = ErrorType<InternalServerErrorResponse>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listOAuthUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListOAuthUsersInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listOAuthUsers>>> = ({ signal }) => listOAuthUsers({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof listOAuthUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListOAuthUsersInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof listOAuthUsers>>>
export type ListOAuthUsersInfiniteQueryError = ErrorType<InternalServerErrorResponse>


export function useListOAuthUsersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listOAuthUsers>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listOAuthUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOAuthUsers>>,
          TError,
          Awaited<ReturnType<typeof listOAuthUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListOAuthUsersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listOAuthUsers>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listOAuthUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOAuthUsers>>,
          TError,
          Awaited<ReturnType<typeof listOAuthUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListOAuthUsersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listOAuthUsers>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listOAuthUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List users
 */

export function useListOAuthUsersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listOAuthUsers>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listOAuthUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListOAuthUsersInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getListOAuthUsersQueryOptions = <TData = Awaited<ReturnType<typeof listOAuthUsers>>, TError = ErrorType<InternalServerErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOAuthUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListOAuthUsersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listOAuthUsers>>> = ({ signal }) => listOAuthUsers({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listOAuthUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListOAuthUsersQueryResult = NonNullable<Awaited<ReturnType<typeof listOAuthUsers>>>
export type ListOAuthUsersQueryError = ErrorType<InternalServerErrorResponse>


export function useListOAuthUsers<TData = Awaited<ReturnType<typeof listOAuthUsers>>, TError = ErrorType<InternalServerErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOAuthUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOAuthUsers>>,
          TError,
          Awaited<ReturnType<typeof listOAuthUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListOAuthUsers<TData = Awaited<ReturnType<typeof listOAuthUsers>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOAuthUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOAuthUsers>>,
          TError,
          Awaited<ReturnType<typeof listOAuthUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListOAuthUsers<TData = Awaited<ReturnType<typeof listOAuthUsers>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOAuthUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List users
 */

export function useListOAuthUsers<TData = Awaited<ReturnType<typeof listOAuthUsers>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOAuthUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListOAuthUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create user
 */
export type createOAuthUserResponse201 = {
  data: OAuthUser
  status: 201
}

export type createOAuthUserResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createOAuthUserResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type createOAuthUserResponseSuccess = (createOAuthUserResponse201) & {
  headers: Headers;
};
export type createOAuthUserResponseError = (createOAuthUserResponse400 | createOAuthUserResponse500) & {
  headers: Headers;
};

export type createOAuthUserResponse = (createOAuthUserResponseSuccess | createOAuthUserResponseError)

export const getCreateOAuthUserUrl = () => {


  

  return `/oauth/users`
}

export const createOAuthUser = async (createUserCommand: CreateUserCommand, options?: RequestInit): Promise<createOAuthUserResponse> => {
  
  return customInstance<createOAuthUserResponse>(getCreateOAuthUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createUserCommand,)
  }
);}




export const getCreateOAuthUserMutationOptions = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOAuthUser>>, TError,{data: BodyType<CreateUserCommand>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createOAuthUser>>, TError,{data: BodyType<CreateUserCommand>}, TContext> => {

const mutationKey = ['createOAuthUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOAuthUser>>, {data: BodyType<CreateUserCommand>}> = (props) => {
          const {data} = props ?? {};

          return  createOAuthUser(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOAuthUserMutationResult = NonNullable<Awaited<ReturnType<typeof createOAuthUser>>>
    export type CreateOAuthUserMutationBody = BodyType<CreateUserCommand>
    export type CreateOAuthUserMutationError = ErrorType<BadRequestResponse | InternalServerErrorResponse>

    /**
 * @summary Create user
 */
export const useCreateOAuthUser = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOAuthUser>>, TError,{data: BodyType<CreateUserCommand>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOAuthUser>>,
        TError,
        {data: BodyType<CreateUserCommand>},
        TContext
      > => {
      return useMutation(getCreateOAuthUserMutationOptions(options), queryClient);
    }
    