/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet/route'
import { Route as TransferProcessRouteImport } from './routes/transfer-process/route'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions/route'
import { Route as ParticipantsRouteImport } from './routes/participants/route'
import { Route as OauthRouteImport } from './routes/oauth/route'
import { Route as MyCatalogRouteImport } from './routes/my-catalog/route'
import { Route as KeystoreRouteImport } from './routes/keystore/route'
import { Route as EventsRouteImport } from './routes/events/route'
import { Route as ContractNegotiationRouteImport } from './routes/contract-negotiation/route'
import { Route as ConnectionsRouteImport } from './routes/connections/route'
import { Route as CatalogRouteImport } from './routes/catalog/route'
import { Route as AuthorityRouteImport } from './routes/authority/route'
import { Route as AgreementsRouteImport } from './routes/agreements/route'
import { Route as IndexImport } from './routes/index'
import { Route as WalletIndexImport } from './routes/wallet/index'
import { Route as TransferProcessIndexImport } from './routes/transfer-process/index'
import { Route as SubscriptionsIndexImport } from './routes/subscriptions/index'
import { Route as ParticipantsIndexImport } from './routes/participants/index'
import { Route as OauthIndexImport } from './routes/oauth/index'
import { Route as MyCatalogIndexImport } from './routes/my-catalog/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as KeystoreIndexImport } from './routes/keystore/index'
import { Route as EventsIndexImport } from './routes/events/index'
import { Route as ContractNegotiationIndexImport } from './routes/contract-negotiation/index'
import { Route as ConnectionsIndexImport } from './routes/connections/index'
import { Route as CatalogIndexImport } from './routes/catalog/index'
import { Route as AuthorityIndexImport } from './routes/authority/index'
import { Route as AgreementsIndexImport } from './routes/agreements/index'
import { Route as WalletOidc4vpImport } from './routes/wallet/oidc4vp'
import { Route as WalletOidc4vciImport } from './routes/wallet/oidc4vci'
import { Route as WalletKeysImport } from './routes/wallet/keys'
import { Route as WalletInfoImport } from './routes/wallet/info'
import { Route as WalletDidImport } from './routes/wallet/did'
import { Route as WalletCredentialsImport } from './routes/wallet/credentials'
import { Route as OauthPatsImport } from './routes/oauth/pats'
import { Route as OauthClientsImport } from './routes/oauth/clients'
import { Route as MyCatalogNewImport } from './routes/my-catalog/new'
import { Route as KeystoreSecretsImport } from './routes/keystore/secrets'
import { Route as KeystoreParametersImport } from './routes/keystore/parameters'
import { Route as KeystoreConfigImport } from './routes/keystore/config'
import { Route as EventsSubscriptionsImport } from './routes/events/subscriptions'
import { Route as EventsFeedImport } from './routes/events/feed'
import { Route as EventsDlqImport } from './routes/events/dlq'
import { Route as AuthorityRequestDetailsImport } from './routes/authority/request-details'
import { Route as AuthorityNewImport } from './routes/authority/new'
import { Route as AgreementsAgreementIdImport } from './routes/agreements/$agreementId'
import { Route as TransferProcessTransferProcessIdRouteImport } from './routes/transfer-process/$transferProcessId/route'
import { Route as ParticipantsParticipantIdRouteImport } from './routes/participants/$participantId/route'
import { Route as ContractNegotiationCnProcessRouteImport } from './routes/contract-negotiation/$cnProcess/route'
import { Route as ConnectionsSentRouteImport } from './routes/connections/sent/route'
import { Route as ConnectionsReceivedRouteImport } from './routes/connections/received/route'
import { Route as CatalogParticipantRouteImport } from './routes/catalog/participant/route'
import { Route as CatalogCatalogIdRouteImport } from './routes/catalog/$catalogId/route'
import { Route as TransferProcessTransferProcessIdIndexImport } from './routes/transfer-process/$transferProcessId/index'
import { Route as ParticipantsParticipantIdIndexImport } from './routes/participants/$participantId/index'
import { Route as ContractNegotiationCnProcessIndexImport } from './routes/contract-negotiation/$cnProcess/index'
import { Route as ConnectionsSentIndexImport } from './routes/connections/sent/index'
import { Route as ConnectionsReceivedIndexImport } from './routes/connections/received/index'
import { Route as CatalogCatalogIdIndexImport } from './routes/catalog/$catalogId/index'
import { Route as ConnectionsSentRequestDetailsImport } from './routes/connections/sent/request-details'
import { Route as ConnectionsSentNewImport } from './routes/connections/sent/new'
import { Route as ConnectionsReceivedRequestDetailsImport } from './routes/connections/received/request-details'
import { Route as CatalogParticipantParticipantIdIndexImport } from './routes/catalog/participant/$participantId/index'
import { Route as TransferProcessTransferProcessIdTransferMessageTransferMessageIdImport } from './routes/transfer-process/$transferProcessId/transfer-message.$transferMessageId'
import { Route as CatalogCatalogIdDistributionConnectorDistributionIdImport } from './routes/catalog/$catalogId/distribution-connector.$distributionId'
import { Route as CatalogCatalogIdDatasetDatasetIdImport } from './routes/catalog/$catalogId/dataset.$datasetId'
import { Route as CatalogCatalogIdDataServiceDataServiceIdImport } from './routes/catalog/$catalogId/data-service.$dataServiceId'
import { Route as CatalogParticipantParticipantIdDatasetDatasetIdImport } from './routes/catalog/participant/$participantId/dataset.$datasetId'

// Create/Update Routes

const WalletRouteRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRoute,
} as any)

const TransferProcessRouteRoute = TransferProcessRouteImport.update({
  id: '/transfer-process',
  path: '/transfer-process',
  getParentRoute: () => rootRoute,
} as any)

const SubscriptionsRouteRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRoute,
} as any)

const ParticipantsRouteRoute = ParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => rootRoute,
} as any)

const OauthRouteRoute = OauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => rootRoute,
} as any)

const MyCatalogRouteRoute = MyCatalogRouteImport.update({
  id: '/my-catalog',
  path: '/my-catalog',
  getParentRoute: () => rootRoute,
} as any)

const KeystoreRouteRoute = KeystoreRouteImport.update({
  id: '/keystore',
  path: '/keystore',
  getParentRoute: () => rootRoute,
} as any)

const EventsRouteRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRoute,
} as any)

const ContractNegotiationRouteRoute = ContractNegotiationRouteImport.update({
  id: '/contract-negotiation',
  path: '/contract-negotiation',
  getParentRoute: () => rootRoute,
} as any)

const ConnectionsRouteRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRoute,
} as any)

const CatalogRouteRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRoute,
} as any)

const AuthorityRouteRoute = AuthorityRouteImport.update({
  id: '/authority',
  path: '/authority',
  getParentRoute: () => rootRoute,
} as any)

const AgreementsRouteRoute = AgreementsRouteImport.update({
  id: '/agreements',
  path: '/agreements',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WalletIndexRoute = WalletIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalletRouteRoute,
} as any)

const TransferProcessIndexRoute = TransferProcessIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransferProcessRouteRoute,
} as any)

const SubscriptionsIndexRoute = SubscriptionsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubscriptionsRouteRoute,
} as any)

const ParticipantsIndexRoute = ParticipantsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParticipantsRouteRoute,
} as any)

const OauthIndexRoute = OauthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OauthRouteRoute,
} as any)

const MyCatalogIndexRoute = MyCatalogIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyCatalogRouteRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const KeystoreIndexRoute = KeystoreIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KeystoreRouteRoute,
} as any)

const EventsIndexRoute = EventsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRouteRoute,
} as any)

const ContractNegotiationIndexRoute = ContractNegotiationIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContractNegotiationRouteRoute,
} as any)

const ConnectionsIndexRoute = ConnectionsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectionsRouteRoute,
} as any)

const CatalogIndexRoute = CatalogIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRouteRoute,
} as any)

const AuthorityIndexRoute = AuthorityIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorityRouteRoute,
} as any)

const AgreementsIndexRoute = AgreementsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgreementsRouteRoute,
} as any)

const WalletOidc4vpRoute = WalletOidc4vpImport.update({
  id: '/oidc4vp',
  path: '/oidc4vp',
  getParentRoute: () => WalletRouteRoute,
} as any)

const WalletOidc4vciRoute = WalletOidc4vciImport.update({
  id: '/oidc4vci',
  path: '/oidc4vci',
  getParentRoute: () => WalletRouteRoute,
} as any)

const WalletKeysRoute = WalletKeysImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => WalletRouteRoute,
} as any)

const WalletInfoRoute = WalletInfoImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => WalletRouteRoute,
} as any)

const WalletDidRoute = WalletDidImport.update({
  id: '/did',
  path: '/did',
  getParentRoute: () => WalletRouteRoute,
} as any)

const WalletCredentialsRoute = WalletCredentialsImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => WalletRouteRoute,
} as any)

const OauthPatsRoute = OauthPatsImport.update({
  id: '/pats',
  path: '/pats',
  getParentRoute: () => OauthRouteRoute,
} as any)

const OauthClientsRoute = OauthClientsImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => OauthRouteRoute,
} as any)

const MyCatalogNewRoute = MyCatalogNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MyCatalogRouteRoute,
} as any)

const KeystoreSecretsRoute = KeystoreSecretsImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => KeystoreRouteRoute,
} as any)

const KeystoreParametersRoute = KeystoreParametersImport.update({
  id: '/parameters',
  path: '/parameters',
  getParentRoute: () => KeystoreRouteRoute,
} as any)

const KeystoreConfigRoute = KeystoreConfigImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => KeystoreRouteRoute,
} as any)

const EventsSubscriptionsRoute = EventsSubscriptionsImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => EventsRouteRoute,
} as any)

const EventsFeedRoute = EventsFeedImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => EventsRouteRoute,
} as any)

const EventsDlqRoute = EventsDlqImport.update({
  id: '/dlq',
  path: '/dlq',
  getParentRoute: () => EventsRouteRoute,
} as any)

const AuthorityRequestDetailsRoute = AuthorityRequestDetailsImport.update({
  id: '/request-details',
  path: '/request-details',
  getParentRoute: () => AuthorityRouteRoute,
} as any)

const AuthorityNewRoute = AuthorityNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthorityRouteRoute,
} as any)

const AgreementsAgreementIdRoute = AgreementsAgreementIdImport.update({
  id: '/$agreementId',
  path: '/$agreementId',
  getParentRoute: () => AgreementsRouteRoute,
} as any)

const TransferProcessTransferProcessIdRouteRoute =
  TransferProcessTransferProcessIdRouteImport.update({
    id: '/$transferProcessId',
    path: '/$transferProcessId',
    getParentRoute: () => TransferProcessRouteRoute,
  } as any)

const ParticipantsParticipantIdRouteRoute =
  ParticipantsParticipantIdRouteImport.update({
    id: '/$participantId',
    path: '/$participantId',
    getParentRoute: () => ParticipantsRouteRoute,
  } as any)

const ContractNegotiationCnProcessRouteRoute =
  ContractNegotiationCnProcessRouteImport.update({
    id: '/$cnProcess',
    path: '/$cnProcess',
    getParentRoute: () => ContractNegotiationRouteRoute,
  } as any)

const ConnectionsSentRouteRoute = ConnectionsSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => ConnectionsRouteRoute,
} as any)

const ConnectionsReceivedRouteRoute = ConnectionsReceivedRouteImport.update({
  id: '/received',
  path: '/received',
  getParentRoute: () => ConnectionsRouteRoute,
} as any)

const CatalogParticipantRouteRoute = CatalogParticipantRouteImport.update({
  id: '/participant',
  path: '/participant',
  getParentRoute: () => CatalogRouteRoute,
} as any)

const CatalogCatalogIdRouteRoute = CatalogCatalogIdRouteImport.update({
  id: '/$catalogId',
  path: '/$catalogId',
  getParentRoute: () => CatalogRouteRoute,
} as any)

const TransferProcessTransferProcessIdIndexRoute =
  TransferProcessTransferProcessIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TransferProcessTransferProcessIdRouteRoute,
  } as any)

const ParticipantsParticipantIdIndexRoute =
  ParticipantsParticipantIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ParticipantsParticipantIdRouteRoute,
  } as any)

const ContractNegotiationCnProcessIndexRoute =
  ContractNegotiationCnProcessIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ContractNegotiationCnProcessRouteRoute,
  } as any)

const ConnectionsSentIndexRoute = ConnectionsSentIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectionsSentRouteRoute,
} as any)

const ConnectionsReceivedIndexRoute = ConnectionsReceivedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectionsReceivedRouteRoute,
} as any)

const CatalogCatalogIdIndexRoute = CatalogCatalogIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogCatalogIdRouteRoute,
} as any)

const ConnectionsSentRequestDetailsRoute =
  ConnectionsSentRequestDetailsImport.update({
    id: '/request-details',
    path: '/request-details',
    getParentRoute: () => ConnectionsSentRouteRoute,
  } as any)

const ConnectionsSentNewRoute = ConnectionsSentNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ConnectionsSentRouteRoute,
} as any)

const ConnectionsReceivedRequestDetailsRoute =
  ConnectionsReceivedRequestDetailsImport.update({
    id: '/request-details',
    path: '/request-details',
    getParentRoute: () => ConnectionsReceivedRouteRoute,
  } as any)

const CatalogParticipantParticipantIdIndexRoute =
  CatalogParticipantParticipantIdIndexImport.update({
    id: '/$participantId/',
    path: '/$participantId/',
    getParentRoute: () => CatalogParticipantRouteRoute,
  } as any)

const TransferProcessTransferProcessIdTransferMessageTransferMessageIdRoute =
  TransferProcessTransferProcessIdTransferMessageTransferMessageIdImport.update(
    {
      id: '/transfer-message/$transferMessageId',
      path: '/transfer-message/$transferMessageId',
      getParentRoute: () => TransferProcessTransferProcessIdRouteRoute,
    } as any,
  )

const CatalogCatalogIdDistributionConnectorDistributionIdRoute =
  CatalogCatalogIdDistributionConnectorDistributionIdImport.update({
    id: '/distribution-connector/$distributionId',
    path: '/distribution-connector/$distributionId',
    getParentRoute: () => CatalogCatalogIdRouteRoute,
  } as any)

const CatalogCatalogIdDatasetDatasetIdRoute =
  CatalogCatalogIdDatasetDatasetIdImport.update({
    id: '/dataset/$datasetId',
    path: '/dataset/$datasetId',
    getParentRoute: () => CatalogCatalogIdRouteRoute,
  } as any)

const CatalogCatalogIdDataServiceDataServiceIdRoute =
  CatalogCatalogIdDataServiceDataServiceIdImport.update({
    id: '/data-service/$dataServiceId',
    path: '/data-service/$dataServiceId',
    getParentRoute: () => CatalogCatalogIdRouteRoute,
  } as any)

const CatalogParticipantParticipantIdDatasetDatasetIdRoute =
  CatalogParticipantParticipantIdDatasetDatasetIdImport.update({
    id: '/$participantId/dataset/$datasetId',
    path: '/$participantId/dataset/$datasetId',
    getParentRoute: () => CatalogParticipantRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/agreements': {
      id: '/agreements'
      path: '/agreements'
      fullPath: '/agreements'
      preLoaderRoute: typeof AgreementsRouteImport
      parentRoute: typeof rootRoute
    }
    '/authority': {
      id: '/authority'
      path: '/authority'
      fullPath: '/authority'
      preLoaderRoute: typeof AuthorityRouteImport
      parentRoute: typeof rootRoute
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRoute
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRoute
    }
    '/contract-negotiation': {
      id: '/contract-negotiation'
      path: '/contract-negotiation'
      fullPath: '/contract-negotiation'
      preLoaderRoute: typeof ContractNegotiationRouteImport
      parentRoute: typeof rootRoute
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRoute
    }
    '/keystore': {
      id: '/keystore'
      path: '/keystore'
      fullPath: '/keystore'
      preLoaderRoute: typeof KeystoreRouteImport
      parentRoute: typeof rootRoute
    }
    '/my-catalog': {
      id: '/my-catalog'
      path: '/my-catalog'
      fullPath: '/my-catalog'
      preLoaderRoute: typeof MyCatalogRouteImport
      parentRoute: typeof rootRoute
    }
    '/oauth': {
      id: '/oauth'
      path: '/oauth'
      fullPath: '/oauth'
      preLoaderRoute: typeof OauthRouteImport
      parentRoute: typeof rootRoute
    }
    '/participants': {
      id: '/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof ParticipantsRouteImport
      parentRoute: typeof rootRoute
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRoute
    }
    '/transfer-process': {
      id: '/transfer-process'
      path: '/transfer-process'
      fullPath: '/transfer-process'
      preLoaderRoute: typeof TransferProcessRouteImport
      parentRoute: typeof rootRoute
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRoute
    }
    '/catalog/$catalogId': {
      id: '/catalog/$catalogId'
      path: '/$catalogId'
      fullPath: '/catalog/$catalogId'
      preLoaderRoute: typeof CatalogCatalogIdRouteImport
      parentRoute: typeof CatalogRouteImport
    }
    '/catalog/participant': {
      id: '/catalog/participant'
      path: '/participant'
      fullPath: '/catalog/participant'
      preLoaderRoute: typeof CatalogParticipantRouteImport
      parentRoute: typeof CatalogRouteImport
    }
    '/connections/received': {
      id: '/connections/received'
      path: '/received'
      fullPath: '/connections/received'
      preLoaderRoute: typeof ConnectionsReceivedRouteImport
      parentRoute: typeof ConnectionsRouteImport
    }
    '/connections/sent': {
      id: '/connections/sent'
      path: '/sent'
      fullPath: '/connections/sent'
      preLoaderRoute: typeof ConnectionsSentRouteImport
      parentRoute: typeof ConnectionsRouteImport
    }
    '/contract-negotiation/$cnProcess': {
      id: '/contract-negotiation/$cnProcess'
      path: '/$cnProcess'
      fullPath: '/contract-negotiation/$cnProcess'
      preLoaderRoute: typeof ContractNegotiationCnProcessRouteImport
      parentRoute: typeof ContractNegotiationRouteImport
    }
    '/participants/$participantId': {
      id: '/participants/$participantId'
      path: '/$participantId'
      fullPath: '/participants/$participantId'
      preLoaderRoute: typeof ParticipantsParticipantIdRouteImport
      parentRoute: typeof ParticipantsRouteImport
    }
    '/transfer-process/$transferProcessId': {
      id: '/transfer-process/$transferProcessId'
      path: '/$transferProcessId'
      fullPath: '/transfer-process/$transferProcessId'
      preLoaderRoute: typeof TransferProcessTransferProcessIdRouteImport
      parentRoute: typeof TransferProcessRouteImport
    }
    '/agreements/$agreementId': {
      id: '/agreements/$agreementId'
      path: '/$agreementId'
      fullPath: '/agreements/$agreementId'
      preLoaderRoute: typeof AgreementsAgreementIdImport
      parentRoute: typeof AgreementsRouteImport
    }
    '/authority/new': {
      id: '/authority/new'
      path: '/new'
      fullPath: '/authority/new'
      preLoaderRoute: typeof AuthorityNewImport
      parentRoute: typeof AuthorityRouteImport
    }
    '/authority/request-details': {
      id: '/authority/request-details'
      path: '/request-details'
      fullPath: '/authority/request-details'
      preLoaderRoute: typeof AuthorityRequestDetailsImport
      parentRoute: typeof AuthorityRouteImport
    }
    '/events/dlq': {
      id: '/events/dlq'
      path: '/dlq'
      fullPath: '/events/dlq'
      preLoaderRoute: typeof EventsDlqImport
      parentRoute: typeof EventsRouteImport
    }
    '/events/feed': {
      id: '/events/feed'
      path: '/feed'
      fullPath: '/events/feed'
      preLoaderRoute: typeof EventsFeedImport
      parentRoute: typeof EventsRouteImport
    }
    '/events/subscriptions': {
      id: '/events/subscriptions'
      path: '/subscriptions'
      fullPath: '/events/subscriptions'
      preLoaderRoute: typeof EventsSubscriptionsImport
      parentRoute: typeof EventsRouteImport
    }
    '/keystore/config': {
      id: '/keystore/config'
      path: '/config'
      fullPath: '/keystore/config'
      preLoaderRoute: typeof KeystoreConfigImport
      parentRoute: typeof KeystoreRouteImport
    }
    '/keystore/parameters': {
      id: '/keystore/parameters'
      path: '/parameters'
      fullPath: '/keystore/parameters'
      preLoaderRoute: typeof KeystoreParametersImport
      parentRoute: typeof KeystoreRouteImport
    }
    '/keystore/secrets': {
      id: '/keystore/secrets'
      path: '/secrets'
      fullPath: '/keystore/secrets'
      preLoaderRoute: typeof KeystoreSecretsImport
      parentRoute: typeof KeystoreRouteImport
    }
    '/my-catalog/new': {
      id: '/my-catalog/new'
      path: '/new'
      fullPath: '/my-catalog/new'
      preLoaderRoute: typeof MyCatalogNewImport
      parentRoute: typeof MyCatalogRouteImport
    }
    '/oauth/clients': {
      id: '/oauth/clients'
      path: '/clients'
      fullPath: '/oauth/clients'
      preLoaderRoute: typeof OauthClientsImport
      parentRoute: typeof OauthRouteImport
    }
    '/oauth/pats': {
      id: '/oauth/pats'
      path: '/pats'
      fullPath: '/oauth/pats'
      preLoaderRoute: typeof OauthPatsImport
      parentRoute: typeof OauthRouteImport
    }
    '/wallet/credentials': {
      id: '/wallet/credentials'
      path: '/credentials'
      fullPath: '/wallet/credentials'
      preLoaderRoute: typeof WalletCredentialsImport
      parentRoute: typeof WalletRouteImport
    }
    '/wallet/did': {
      id: '/wallet/did'
      path: '/did'
      fullPath: '/wallet/did'
      preLoaderRoute: typeof WalletDidImport
      parentRoute: typeof WalletRouteImport
    }
    '/wallet/info': {
      id: '/wallet/info'
      path: '/info'
      fullPath: '/wallet/info'
      preLoaderRoute: typeof WalletInfoImport
      parentRoute: typeof WalletRouteImport
    }
    '/wallet/keys': {
      id: '/wallet/keys'
      path: '/keys'
      fullPath: '/wallet/keys'
      preLoaderRoute: typeof WalletKeysImport
      parentRoute: typeof WalletRouteImport
    }
    '/wallet/oidc4vci': {
      id: '/wallet/oidc4vci'
      path: '/oidc4vci'
      fullPath: '/wallet/oidc4vci'
      preLoaderRoute: typeof WalletOidc4vciImport
      parentRoute: typeof WalletRouteImport
    }
    '/wallet/oidc4vp': {
      id: '/wallet/oidc4vp'
      path: '/oidc4vp'
      fullPath: '/wallet/oidc4vp'
      preLoaderRoute: typeof WalletOidc4vpImport
      parentRoute: typeof WalletRouteImport
    }
    '/agreements/': {
      id: '/agreements/'
      path: '/'
      fullPath: '/agreements/'
      preLoaderRoute: typeof AgreementsIndexImport
      parentRoute: typeof AgreementsRouteImport
    }
    '/authority/': {
      id: '/authority/'
      path: '/'
      fullPath: '/authority/'
      preLoaderRoute: typeof AuthorityIndexImport
      parentRoute: typeof AuthorityRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexImport
      parentRoute: typeof CatalogRouteImport
    }
    '/connections/': {
      id: '/connections/'
      path: '/'
      fullPath: '/connections/'
      preLoaderRoute: typeof ConnectionsIndexImport
      parentRoute: typeof ConnectionsRouteImport
    }
    '/contract-negotiation/': {
      id: '/contract-negotiation/'
      path: '/'
      fullPath: '/contract-negotiation/'
      preLoaderRoute: typeof ContractNegotiationIndexImport
      parentRoute: typeof ContractNegotiationRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexImport
      parentRoute: typeof EventsRouteImport
    }
    '/keystore/': {
      id: '/keystore/'
      path: '/'
      fullPath: '/keystore/'
      preLoaderRoute: typeof KeystoreIndexImport
      parentRoute: typeof KeystoreRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/my-catalog/': {
      id: '/my-catalog/'
      path: '/'
      fullPath: '/my-catalog/'
      preLoaderRoute: typeof MyCatalogIndexImport
      parentRoute: typeof MyCatalogRouteImport
    }
    '/oauth/': {
      id: '/oauth/'
      path: '/'
      fullPath: '/oauth/'
      preLoaderRoute: typeof OauthIndexImport
      parentRoute: typeof OauthRouteImport
    }
    '/participants/': {
      id: '/participants/'
      path: '/'
      fullPath: '/participants/'
      preLoaderRoute: typeof ParticipantsIndexImport
      parentRoute: typeof ParticipantsRouteImport
    }
    '/subscriptions/': {
      id: '/subscriptions/'
      path: '/'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof SubscriptionsIndexImport
      parentRoute: typeof SubscriptionsRouteImport
    }
    '/transfer-process/': {
      id: '/transfer-process/'
      path: '/'
      fullPath: '/transfer-process/'
      preLoaderRoute: typeof TransferProcessIndexImport
      parentRoute: typeof TransferProcessRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexImport
      parentRoute: typeof WalletRouteImport
    }
    '/connections/received/request-details': {
      id: '/connections/received/request-details'
      path: '/request-details'
      fullPath: '/connections/received/request-details'
      preLoaderRoute: typeof ConnectionsReceivedRequestDetailsImport
      parentRoute: typeof ConnectionsReceivedRouteImport
    }
    '/connections/sent/new': {
      id: '/connections/sent/new'
      path: '/new'
      fullPath: '/connections/sent/new'
      preLoaderRoute: typeof ConnectionsSentNewImport
      parentRoute: typeof ConnectionsSentRouteImport
    }
    '/connections/sent/request-details': {
      id: '/connections/sent/request-details'
      path: '/request-details'
      fullPath: '/connections/sent/request-details'
      preLoaderRoute: typeof ConnectionsSentRequestDetailsImport
      parentRoute: typeof ConnectionsSentRouteImport
    }
    '/catalog/$catalogId/': {
      id: '/catalog/$catalogId/'
      path: '/'
      fullPath: '/catalog/$catalogId/'
      preLoaderRoute: typeof CatalogCatalogIdIndexImport
      parentRoute: typeof CatalogCatalogIdRouteImport
    }
    '/connections/received/': {
      id: '/connections/received/'
      path: '/'
      fullPath: '/connections/received/'
      preLoaderRoute: typeof ConnectionsReceivedIndexImport
      parentRoute: typeof ConnectionsReceivedRouteImport
    }
    '/connections/sent/': {
      id: '/connections/sent/'
      path: '/'
      fullPath: '/connections/sent/'
      preLoaderRoute: typeof ConnectionsSentIndexImport
      parentRoute: typeof ConnectionsSentRouteImport
    }
    '/contract-negotiation/$cnProcess/': {
      id: '/contract-negotiation/$cnProcess/'
      path: '/'
      fullPath: '/contract-negotiation/$cnProcess/'
      preLoaderRoute: typeof ContractNegotiationCnProcessIndexImport
      parentRoute: typeof ContractNegotiationCnProcessRouteImport
    }
    '/participants/$participantId/': {
      id: '/participants/$participantId/'
      path: '/'
      fullPath: '/participants/$participantId/'
      preLoaderRoute: typeof ParticipantsParticipantIdIndexImport
      parentRoute: typeof ParticipantsParticipantIdRouteImport
    }
    '/transfer-process/$transferProcessId/': {
      id: '/transfer-process/$transferProcessId/'
      path: '/'
      fullPath: '/transfer-process/$transferProcessId/'
      preLoaderRoute: typeof TransferProcessTransferProcessIdIndexImport
      parentRoute: typeof TransferProcessTransferProcessIdRouteImport
    }
    '/catalog/$catalogId/data-service/$dataServiceId': {
      id: '/catalog/$catalogId/data-service/$dataServiceId'
      path: '/data-service/$dataServiceId'
      fullPath: '/catalog/$catalogId/data-service/$dataServiceId'
      preLoaderRoute: typeof CatalogCatalogIdDataServiceDataServiceIdImport
      parentRoute: typeof CatalogCatalogIdRouteImport
    }
    '/catalog/$catalogId/dataset/$datasetId': {
      id: '/catalog/$catalogId/dataset/$datasetId'
      path: '/dataset/$datasetId'
      fullPath: '/catalog/$catalogId/dataset/$datasetId'
      preLoaderRoute: typeof CatalogCatalogIdDatasetDatasetIdImport
      parentRoute: typeof CatalogCatalogIdRouteImport
    }
    '/catalog/$catalogId/distribution-connector/$distributionId': {
      id: '/catalog/$catalogId/distribution-connector/$distributionId'
      path: '/distribution-connector/$distributionId'
      fullPath: '/catalog/$catalogId/distribution-connector/$distributionId'
      preLoaderRoute: typeof CatalogCatalogIdDistributionConnectorDistributionIdImport
      parentRoute: typeof CatalogCatalogIdRouteImport
    }
    '/transfer-process/$transferProcessId/transfer-message/$transferMessageId': {
      id: '/transfer-process/$transferProcessId/transfer-message/$transferMessageId'
      path: '/transfer-message/$transferMessageId'
      fullPath: '/transfer-process/$transferProcessId/transfer-message/$transferMessageId'
      preLoaderRoute: typeof TransferProcessTransferProcessIdTransferMessageTransferMessageIdImport
      parentRoute: typeof TransferProcessTransferProcessIdRouteImport
    }
    '/catalog/participant/$participantId/': {
      id: '/catalog/participant/$participantId/'
      path: '/$participantId'
      fullPath: '/catalog/participant/$participantId'
      preLoaderRoute: typeof CatalogParticipantParticipantIdIndexImport
      parentRoute: typeof CatalogParticipantRouteImport
    }
    '/catalog/participant/$participantId/dataset/$datasetId': {
      id: '/catalog/participant/$participantId/dataset/$datasetId'
      path: '/$participantId/dataset/$datasetId'
      fullPath: '/catalog/participant/$participantId/dataset/$datasetId'
      preLoaderRoute: typeof CatalogParticipantParticipantIdDatasetDatasetIdImport
      parentRoute: typeof CatalogParticipantRouteImport
    }
  }
}

// Create and export the route tree

interface AgreementsRouteRouteChildren {
  AgreementsAgreementIdRoute: typeof AgreementsAgreementIdRoute
  AgreementsIndexRoute: typeof AgreementsIndexRoute
}

const AgreementsRouteRouteChildren: AgreementsRouteRouteChildren = {
  AgreementsAgreementIdRoute: AgreementsAgreementIdRoute,
  AgreementsIndexRoute: AgreementsIndexRoute,
}

const AgreementsRouteRouteWithChildren = AgreementsRouteRoute._addFileChildren(
  AgreementsRouteRouteChildren,
)

interface AuthorityRouteRouteChildren {
  AuthorityNewRoute: typeof AuthorityNewRoute
  AuthorityRequestDetailsRoute: typeof AuthorityRequestDetailsRoute
  AuthorityIndexRoute: typeof AuthorityIndexRoute
}

const AuthorityRouteRouteChildren: AuthorityRouteRouteChildren = {
  AuthorityNewRoute: AuthorityNewRoute,
  AuthorityRequestDetailsRoute: AuthorityRequestDetailsRoute,
  AuthorityIndexRoute: AuthorityIndexRoute,
}

const AuthorityRouteRouteWithChildren = AuthorityRouteRoute._addFileChildren(
  AuthorityRouteRouteChildren,
)

interface CatalogCatalogIdRouteRouteChildren {
  CatalogCatalogIdIndexRoute: typeof CatalogCatalogIdIndexRoute
  CatalogCatalogIdDataServiceDataServiceIdRoute: typeof CatalogCatalogIdDataServiceDataServiceIdRoute
  CatalogCatalogIdDatasetDatasetIdRoute: typeof CatalogCatalogIdDatasetDatasetIdRoute
  CatalogCatalogIdDistributionConnectorDistributionIdRoute: typeof CatalogCatalogIdDistributionConnectorDistributionIdRoute
}

const CatalogCatalogIdRouteRouteChildren: CatalogCatalogIdRouteRouteChildren = {
  CatalogCatalogIdIndexRoute: CatalogCatalogIdIndexRoute,
  CatalogCatalogIdDataServiceDataServiceIdRoute:
    CatalogCatalogIdDataServiceDataServiceIdRoute,
  CatalogCatalogIdDatasetDatasetIdRoute: CatalogCatalogIdDatasetDatasetIdRoute,
  CatalogCatalogIdDistributionConnectorDistributionIdRoute:
    CatalogCatalogIdDistributionConnectorDistributionIdRoute,
}

const CatalogCatalogIdRouteRouteWithChildren =
  CatalogCatalogIdRouteRoute._addFileChildren(
    CatalogCatalogIdRouteRouteChildren,
  )

interface CatalogParticipantRouteRouteChildren {
  CatalogParticipantParticipantIdIndexRoute: typeof CatalogParticipantParticipantIdIndexRoute
  CatalogParticipantParticipantIdDatasetDatasetIdRoute: typeof CatalogParticipantParticipantIdDatasetDatasetIdRoute
}

const CatalogParticipantRouteRouteChildren: CatalogParticipantRouteRouteChildren =
  {
    CatalogParticipantParticipantIdIndexRoute:
      CatalogParticipantParticipantIdIndexRoute,
    CatalogParticipantParticipantIdDatasetDatasetIdRoute:
      CatalogParticipantParticipantIdDatasetDatasetIdRoute,
  }

const CatalogParticipantRouteRouteWithChildren =
  CatalogParticipantRouteRoute._addFileChildren(
    CatalogParticipantRouteRouteChildren,
  )

interface CatalogRouteRouteChildren {
  CatalogCatalogIdRouteRoute: typeof CatalogCatalogIdRouteRouteWithChildren
  CatalogParticipantRouteRoute: typeof CatalogParticipantRouteRouteWithChildren
  CatalogIndexRoute: typeof CatalogIndexRoute
}

const CatalogRouteRouteChildren: CatalogRouteRouteChildren = {
  CatalogCatalogIdRouteRoute: CatalogCatalogIdRouteRouteWithChildren,
  CatalogParticipantRouteRoute: CatalogParticipantRouteRouteWithChildren,
  CatalogIndexRoute: CatalogIndexRoute,
}

const CatalogRouteRouteWithChildren = CatalogRouteRoute._addFileChildren(
  CatalogRouteRouteChildren,
)

interface ConnectionsReceivedRouteRouteChildren {
  ConnectionsReceivedRequestDetailsRoute: typeof ConnectionsReceivedRequestDetailsRoute
  ConnectionsReceivedIndexRoute: typeof ConnectionsReceivedIndexRoute
}

const ConnectionsReceivedRouteRouteChildren: ConnectionsReceivedRouteRouteChildren =
  {
    ConnectionsReceivedRequestDetailsRoute:
      ConnectionsReceivedRequestDetailsRoute,
    ConnectionsReceivedIndexRoute: ConnectionsReceivedIndexRoute,
  }

const ConnectionsReceivedRouteRouteWithChildren =
  ConnectionsReceivedRouteRoute._addFileChildren(
    ConnectionsReceivedRouteRouteChildren,
  )

interface ConnectionsSentRouteRouteChildren {
  ConnectionsSentNewRoute: typeof ConnectionsSentNewRoute
  ConnectionsSentRequestDetailsRoute: typeof ConnectionsSentRequestDetailsRoute
  ConnectionsSentIndexRoute: typeof ConnectionsSentIndexRoute
}

const ConnectionsSentRouteRouteChildren: ConnectionsSentRouteRouteChildren = {
  ConnectionsSentNewRoute: ConnectionsSentNewRoute,
  ConnectionsSentRequestDetailsRoute: ConnectionsSentRequestDetailsRoute,
  ConnectionsSentIndexRoute: ConnectionsSentIndexRoute,
}

const ConnectionsSentRouteRouteWithChildren =
  ConnectionsSentRouteRoute._addFileChildren(ConnectionsSentRouteRouteChildren)

interface ConnectionsRouteRouteChildren {
  ConnectionsReceivedRouteRoute: typeof ConnectionsReceivedRouteRouteWithChildren
  ConnectionsSentRouteRoute: typeof ConnectionsSentRouteRouteWithChildren
  ConnectionsIndexRoute: typeof ConnectionsIndexRoute
}

const ConnectionsRouteRouteChildren: ConnectionsRouteRouteChildren = {
  ConnectionsReceivedRouteRoute: ConnectionsReceivedRouteRouteWithChildren,
  ConnectionsSentRouteRoute: ConnectionsSentRouteRouteWithChildren,
  ConnectionsIndexRoute: ConnectionsIndexRoute,
}

const ConnectionsRouteRouteWithChildren =
  ConnectionsRouteRoute._addFileChildren(ConnectionsRouteRouteChildren)

interface ContractNegotiationCnProcessRouteRouteChildren {
  ContractNegotiationCnProcessIndexRoute: typeof ContractNegotiationCnProcessIndexRoute
}

const ContractNegotiationCnProcessRouteRouteChildren: ContractNegotiationCnProcessRouteRouteChildren =
  {
    ContractNegotiationCnProcessIndexRoute:
      ContractNegotiationCnProcessIndexRoute,
  }

const ContractNegotiationCnProcessRouteRouteWithChildren =
  ContractNegotiationCnProcessRouteRoute._addFileChildren(
    ContractNegotiationCnProcessRouteRouteChildren,
  )

interface ContractNegotiationRouteRouteChildren {
  ContractNegotiationCnProcessRouteRoute: typeof ContractNegotiationCnProcessRouteRouteWithChildren
  ContractNegotiationIndexRoute: typeof ContractNegotiationIndexRoute
}

const ContractNegotiationRouteRouteChildren: ContractNegotiationRouteRouteChildren =
  {
    ContractNegotiationCnProcessRouteRoute:
      ContractNegotiationCnProcessRouteRouteWithChildren,
    ContractNegotiationIndexRoute: ContractNegotiationIndexRoute,
  }

const ContractNegotiationRouteRouteWithChildren =
  ContractNegotiationRouteRoute._addFileChildren(
    ContractNegotiationRouteRouteChildren,
  )

interface EventsRouteRouteChildren {
  EventsDlqRoute: typeof EventsDlqRoute
  EventsFeedRoute: typeof EventsFeedRoute
  EventsSubscriptionsRoute: typeof EventsSubscriptionsRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteRouteChildren: EventsRouteRouteChildren = {
  EventsDlqRoute: EventsDlqRoute,
  EventsFeedRoute: EventsFeedRoute,
  EventsSubscriptionsRoute: EventsSubscriptionsRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteRouteWithChildren = EventsRouteRoute._addFileChildren(
  EventsRouteRouteChildren,
)

interface KeystoreRouteRouteChildren {
  KeystoreConfigRoute: typeof KeystoreConfigRoute
  KeystoreParametersRoute: typeof KeystoreParametersRoute
  KeystoreSecretsRoute: typeof KeystoreSecretsRoute
  KeystoreIndexRoute: typeof KeystoreIndexRoute
}

const KeystoreRouteRouteChildren: KeystoreRouteRouteChildren = {
  KeystoreConfigRoute: KeystoreConfigRoute,
  KeystoreParametersRoute: KeystoreParametersRoute,
  KeystoreSecretsRoute: KeystoreSecretsRoute,
  KeystoreIndexRoute: KeystoreIndexRoute,
}

const KeystoreRouteRouteWithChildren = KeystoreRouteRoute._addFileChildren(
  KeystoreRouteRouteChildren,
)

interface MyCatalogRouteRouteChildren {
  MyCatalogNewRoute: typeof MyCatalogNewRoute
  MyCatalogIndexRoute: typeof MyCatalogIndexRoute
}

const MyCatalogRouteRouteChildren: MyCatalogRouteRouteChildren = {
  MyCatalogNewRoute: MyCatalogNewRoute,
  MyCatalogIndexRoute: MyCatalogIndexRoute,
}

const MyCatalogRouteRouteWithChildren = MyCatalogRouteRoute._addFileChildren(
  MyCatalogRouteRouteChildren,
)

interface OauthRouteRouteChildren {
  OauthClientsRoute: typeof OauthClientsRoute
  OauthPatsRoute: typeof OauthPatsRoute
  OauthIndexRoute: typeof OauthIndexRoute
}

const OauthRouteRouteChildren: OauthRouteRouteChildren = {
  OauthClientsRoute: OauthClientsRoute,
  OauthPatsRoute: OauthPatsRoute,
  OauthIndexRoute: OauthIndexRoute,
}

const OauthRouteRouteWithChildren = OauthRouteRoute._addFileChildren(
  OauthRouteRouteChildren,
)

interface ParticipantsParticipantIdRouteRouteChildren {
  ParticipantsParticipantIdIndexRoute: typeof ParticipantsParticipantIdIndexRoute
}

const ParticipantsParticipantIdRouteRouteChildren: ParticipantsParticipantIdRouteRouteChildren =
  {
    ParticipantsParticipantIdIndexRoute: ParticipantsParticipantIdIndexRoute,
  }

const ParticipantsParticipantIdRouteRouteWithChildren =
  ParticipantsParticipantIdRouteRoute._addFileChildren(
    ParticipantsParticipantIdRouteRouteChildren,
  )

interface ParticipantsRouteRouteChildren {
  ParticipantsParticipantIdRouteRoute: typeof ParticipantsParticipantIdRouteRouteWithChildren
  ParticipantsIndexRoute: typeof ParticipantsIndexRoute
}

const ParticipantsRouteRouteChildren: ParticipantsRouteRouteChildren = {
  ParticipantsParticipantIdRouteRoute:
    ParticipantsParticipantIdRouteRouteWithChildren,
  ParticipantsIndexRoute: ParticipantsIndexRoute,
}

const ParticipantsRouteRouteWithChildren =
  ParticipantsRouteRoute._addFileChildren(ParticipantsRouteRouteChildren)

interface SubscriptionsRouteRouteChildren {
  SubscriptionsIndexRoute: typeof SubscriptionsIndexRoute
}

const SubscriptionsRouteRouteChildren: SubscriptionsRouteRouteChildren = {
  SubscriptionsIndexRoute: SubscriptionsIndexRoute,
}

const SubscriptionsRouteRouteWithChildren =
  SubscriptionsRouteRoute._addFileChildren(SubscriptionsRouteRouteChildren)

interface TransferProcessTransferProcessIdRouteRouteChildren {
  TransferProcessTransferProcessIdIndexRoute: typeof TransferProcessTransferProcessIdIndexRoute
  TransferProcessTransferProcessIdTransferMessageTransferMessageIdRoute: typeof TransferProcessTransferProcessIdTransferMessageTransferMessageIdRoute
}

const TransferProcessTransferProcessIdRouteRouteChildren: TransferProcessTransferProcessIdRouteRouteChildren =
  {
    TransferProcessTransferProcessIdIndexRoute:
      TransferProcessTransferProcessIdIndexRoute,
    TransferProcessTransferProcessIdTransferMessageTransferMessageIdRoute:
      TransferProcessTransferProcessIdTransferMessageTransferMessageIdRoute,
  }

const TransferProcessTransferProcessIdRouteRouteWithChildren =
  TransferProcessTransferProcessIdRouteRoute._addFileChildren(
    TransferProcessTransferProcessIdRouteRouteChildren,
  )

interface TransferProcessRouteRouteChildren {
  TransferProcessTransferProcessIdRouteRoute: typeof TransferProcessTransferProcessIdRouteRouteWithChildren
  TransferProcessIndexRoute: typeof TransferProcessIndexRoute
}

const TransferProcessRouteRouteChildren: TransferProcessRouteRouteChildren = {
  TransferProcessTransferProcessIdRouteRoute:
    TransferProcessTransferProcessIdRouteRouteWithChildren,
  TransferProcessIndexRoute: TransferProcessIndexRoute,
}

const TransferProcessRouteRouteWithChildren =
  TransferProcessRouteRoute._addFileChildren(TransferProcessRouteRouteChildren)

interface WalletRouteRouteChildren {
  WalletCredentialsRoute: typeof WalletCredentialsRoute
  WalletDidRoute: typeof WalletDidRoute
  WalletInfoRoute: typeof WalletInfoRoute
  WalletKeysRoute: typeof WalletKeysRoute
  WalletOidc4vciRoute: typeof WalletOidc4vciRoute
  WalletOidc4vpRoute: typeof WalletOidc4vpRoute
  WalletIndexRoute: typeof WalletIndexRoute
}

const WalletRouteRouteChildren: WalletRouteRouteChildren = {
  WalletCredentialsRoute: WalletCredentialsRoute,
  WalletDidRoute: WalletDidRoute,
  WalletInfoRoute: WalletInfoRoute,
  WalletKeysRoute: WalletKeysRoute,
  WalletOidc4vciRoute: WalletOidc4vciRoute,
  WalletOidc4vpRoute: WalletOidc4vpRoute,
  WalletIndexRoute: WalletIndexRoute,
}

const WalletRouteRouteWithChildren = WalletRouteRoute._addFileChildren(
  WalletRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agreements': typeof AgreementsRouteRouteWithChildren
  '/authority': typeof AuthorityRouteRouteWithChildren
  '/catalog': typeof CatalogRouteRouteWithChildren
  '/connections': typeof ConnectionsRouteRouteWithChildren
  '/contract-negotiation': typeof ContractNegotiationRouteRouteWithChildren
  '/events': typeof EventsRouteRouteWithChildren
  '/keystore': typeof KeystoreRouteRouteWithChildren
  '/my-catalog': typeof MyCatalogRouteRouteWithChildren
  '/oauth': typeof OauthRouteRouteWithChildren
  '/participants': typeof ParticipantsRouteRouteWithChildren
  '/subscriptions': typeof SubscriptionsRouteRouteWithChildren
  '/transfer-process': typeof TransferProcessRouteRouteWithChildren
  '/wallet': typeof WalletRouteRouteWithChildren
  '/catalog/$catalogId': typeof CatalogCatalogIdRouteRouteWithChildren
  '/catalog/participant': typeof CatalogParticipantRouteRouteWithChildren
  '/connections/received': typeof ConnectionsReceivedRouteRouteWithChildren
  '/connections/sent': typeof ConnectionsSentRouteRouteWithChildren
  '/contract-negotiation/$cnProcess': typeof ContractNegotiationCnProcessRouteRouteWithChildren
  '/participants/$participantId': typeof ParticipantsParticipantIdRouteRouteWithChildren
  '/transfer-process/$transferProcessId': typeof TransferProcessTransferProcessIdRouteRouteWithChildren
  '/agreements/$agreementId': typeof AgreementsAgreementIdRoute
  '/authority/new': typeof AuthorityNewRoute
  '/authority/request-details': typeof AuthorityRequestDetailsRoute
  '/events/dlq': typeof EventsDlqRoute
  '/events/feed': typeof EventsFeedRoute
  '/events/subscriptions': typeof EventsSubscriptionsRoute
  '/keystore/config': typeof KeystoreConfigRoute
  '/keystore/parameters': typeof KeystoreParametersRoute
  '/keystore/secrets': typeof KeystoreSecretsRoute
  '/my-catalog/new': typeof MyCatalogNewRoute
  '/oauth/clients': typeof OauthClientsRoute
  '/oauth/pats': typeof OauthPatsRoute
  '/wallet/credentials': typeof WalletCredentialsRoute
  '/wallet/did': typeof WalletDidRoute
  '/wallet/info': typeof WalletInfoRoute
  '/wallet/keys': typeof WalletKeysRoute
  '/wallet/oidc4vci': typeof WalletOidc4vciRoute
  '/wallet/oidc4vp': typeof WalletOidc4vpRoute
  '/agreements/': typeof AgreementsIndexRoute
  '/authority/': typeof AuthorityIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/connections/': typeof ConnectionsIndexRoute
  '/contract-negotiation/': typeof ContractNegotiationIndexRoute
  '/events/': typeof EventsIndexRoute
  '/keystore/': typeof KeystoreIndexRoute
  '/login': typeof LoginIndexRoute
  '/my-catalog/': typeof MyCatalogIndexRoute
  '/oauth/': typeof OauthIndexRoute
  '/participants/': typeof ParticipantsIndexRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
  '/transfer-process/': typeof TransferProcessIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/connections/received/request-details': typeof ConnectionsReceivedRequestDetailsRoute
  '/connections/sent/new': typeof ConnectionsSentNewRoute
  '/connections/sent/request-details': typeof ConnectionsSentRequestDetailsRoute
  '/catalog/$catalogId/': typeof CatalogCatalogIdIndexRoute
  '/connections/received/': typeof ConnectionsReceivedIndexRoute
  '/connections/sent/': typeof ConnectionsSentIndexRoute
  '/contract-negotiation/$cnProcess/': typeof ContractNegotiationCnProcessIndexRoute
  '/participants/$participantId/': typeof ParticipantsParticipantIdIndexRoute
  '/transfer-process/$transferProcessId/': typeof TransferProcessTransferProcessIdIndexRoute
  '/catalog/$catalogId/data-service/$dataServiceId': typeof CatalogCatalogIdDataServiceDataServiceIdRoute
  '/catalog/$catalogId/dataset/$datasetId': typeof CatalogCatalogIdDatasetDatasetIdRoute
  '/catalog/$catalogId/distribution-connector/$distributionId': typeof CatalogCatalogIdDistributionConnectorDistributionIdRoute
  '/transfer-process/$transferProcessId/transfer-message/$transferMessageId': typeof TransferProcessTransferProcessIdTransferMessageTransferMessageIdRoute
  '/catalog/participant/$participantId': typeof CatalogParticipantParticipantIdIndexRoute
  '/catalog/participant/$participantId/dataset/$datasetId': typeof CatalogParticipantParticipantIdDatasetDatasetIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog/participant': typeof CatalogParticipantRouteRouteWithChildren
  '/agreements/$agreementId': typeof AgreementsAgreementIdRoute
  '/authority/new': typeof AuthorityNewRoute
  '/authority/request-details': typeof AuthorityRequestDetailsRoute
  '/events/dlq': typeof EventsDlqRoute
  '/events/feed': typeof EventsFeedRoute
  '/events/subscriptions': typeof EventsSubscriptionsRoute
  '/keystore/config': typeof KeystoreConfigRoute
  '/keystore/parameters': typeof KeystoreParametersRoute
  '/keystore/secrets': typeof KeystoreSecretsRoute
  '/my-catalog/new': typeof MyCatalogNewRoute
  '/oauth/clients': typeof OauthClientsRoute
  '/oauth/pats': typeof OauthPatsRoute
  '/wallet/credentials': typeof WalletCredentialsRoute
  '/wallet/did': typeof WalletDidRoute
  '/wallet/info': typeof WalletInfoRoute
  '/wallet/keys': typeof WalletKeysRoute
  '/wallet/oidc4vci': typeof WalletOidc4vciRoute
  '/wallet/oidc4vp': typeof WalletOidc4vpRoute
  '/agreements': typeof AgreementsIndexRoute
  '/authority': typeof AuthorityIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/connections': typeof ConnectionsIndexRoute
  '/contract-negotiation': typeof ContractNegotiationIndexRoute
  '/events': typeof EventsIndexRoute
  '/keystore': typeof KeystoreIndexRoute
  '/login': typeof LoginIndexRoute
  '/my-catalog': typeof MyCatalogIndexRoute
  '/oauth': typeof OauthIndexRoute
  '/participants': typeof ParticipantsIndexRoute
  '/subscriptions': typeof SubscriptionsIndexRoute
  '/transfer-process': typeof TransferProcessIndexRoute
  '/wallet': typeof WalletIndexRoute
  '/connections/received/request-details': typeof ConnectionsReceivedRequestDetailsRoute
  '/connections/sent/new': typeof ConnectionsSentNewRoute
  '/connections/sent/request-details': typeof ConnectionsSentRequestDetailsRoute
  '/catalog/$catalogId': typeof CatalogCatalogIdIndexRoute
  '/connections/received': typeof ConnectionsReceivedIndexRoute
  '/connections/sent': typeof ConnectionsSentIndexRoute
  '/contract-negotiation/$cnProcess': typeof ContractNegotiationCnProcessIndexRoute
  '/participants/$participantId': typeof ParticipantsParticipantIdIndexRoute
  '/transfer-process/$transferProcessId': typeof TransferProcessTransferProcessIdIndexRoute
  '/catalog/$catalogId/data-service/$dataServiceId': typeof CatalogCatalogIdDataServiceDataServiceIdRoute
  '/catalog/$catalogId/dataset/$datasetId': typeof CatalogCatalogIdDatasetDatasetIdRoute
  '/catalog/$catalogId/distribution-connector/$distributionId': typeof CatalogCatalogIdDistributionConnectorDistributionIdRoute
  '/transfer-process/$transferProcessId/transfer-message/$transferMessageId': typeof TransferProcessTransferProcessIdTransferMessageTransferMessageIdRoute
  '/catalog/participant/$participantId': typeof CatalogParticipantParticipantIdIndexRoute
  '/catalog/participant/$participantId/dataset/$datasetId': typeof CatalogParticipantParticipantIdDatasetDatasetIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/agreements': typeof AgreementsRouteRouteWithChildren
  '/authority': typeof AuthorityRouteRouteWithChildren
  '/catalog': typeof CatalogRouteRouteWithChildren
  '/connections': typeof ConnectionsRouteRouteWithChildren
  '/contract-negotiation': typeof ContractNegotiationRouteRouteWithChildren
  '/events': typeof EventsRouteRouteWithChildren
  '/keystore': typeof KeystoreRouteRouteWithChildren
  '/my-catalog': typeof MyCatalogRouteRouteWithChildren
  '/oauth': typeof OauthRouteRouteWithChildren
  '/participants': typeof ParticipantsRouteRouteWithChildren
  '/subscriptions': typeof SubscriptionsRouteRouteWithChildren
  '/transfer-process': typeof TransferProcessRouteRouteWithChildren
  '/wallet': typeof WalletRouteRouteWithChildren
  '/catalog/$catalogId': typeof CatalogCatalogIdRouteRouteWithChildren
  '/catalog/participant': typeof CatalogParticipantRouteRouteWithChildren
  '/connections/received': typeof ConnectionsReceivedRouteRouteWithChildren
  '/connections/sent': typeof ConnectionsSentRouteRouteWithChildren
  '/contract-negotiation/$cnProcess': typeof ContractNegotiationCnProcessRouteRouteWithChildren
  '/participants/$participantId': typeof ParticipantsParticipantIdRouteRouteWithChildren
  '/transfer-process/$transferProcessId': typeof TransferProcessTransferProcessIdRouteRouteWithChildren
  '/agreements/$agreementId': typeof AgreementsAgreementIdRoute
  '/authority/new': typeof AuthorityNewRoute
  '/authority/request-details': typeof AuthorityRequestDetailsRoute
  '/events/dlq': typeof EventsDlqRoute
  '/events/feed': typeof EventsFeedRoute
  '/events/subscriptions': typeof EventsSubscriptionsRoute
  '/keystore/config': typeof KeystoreConfigRoute
  '/keystore/parameters': typeof KeystoreParametersRoute
  '/keystore/secrets': typeof KeystoreSecretsRoute
  '/my-catalog/new': typeof MyCatalogNewRoute
  '/oauth/clients': typeof OauthClientsRoute
  '/oauth/pats': typeof OauthPatsRoute
  '/wallet/credentials': typeof WalletCredentialsRoute
  '/wallet/did': typeof WalletDidRoute
  '/wallet/info': typeof WalletInfoRoute
  '/wallet/keys': typeof WalletKeysRoute
  '/wallet/oidc4vci': typeof WalletOidc4vciRoute
  '/wallet/oidc4vp': typeof WalletOidc4vpRoute
  '/agreements/': typeof AgreementsIndexRoute
  '/authority/': typeof AuthorityIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/connections/': typeof ConnectionsIndexRoute
  '/contract-negotiation/': typeof ContractNegotiationIndexRoute
  '/events/': typeof EventsIndexRoute
  '/keystore/': typeof KeystoreIndexRoute
  '/login/': typeof LoginIndexRoute
  '/my-catalog/': typeof MyCatalogIndexRoute
  '/oauth/': typeof OauthIndexRoute
  '/participants/': typeof ParticipantsIndexRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
  '/transfer-process/': typeof TransferProcessIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/connections/received/request-details': typeof ConnectionsReceivedRequestDetailsRoute
  '/connections/sent/new': typeof ConnectionsSentNewRoute
  '/connections/sent/request-details': typeof ConnectionsSentRequestDetailsRoute
  '/catalog/$catalogId/': typeof CatalogCatalogIdIndexRoute
  '/connections/received/': typeof ConnectionsReceivedIndexRoute
  '/connections/sent/': typeof ConnectionsSentIndexRoute
  '/contract-negotiation/$cnProcess/': typeof ContractNegotiationCnProcessIndexRoute
  '/participants/$participantId/': typeof ParticipantsParticipantIdIndexRoute
  '/transfer-process/$transferProcessId/': typeof TransferProcessTransferProcessIdIndexRoute
  '/catalog/$catalogId/data-service/$dataServiceId': typeof CatalogCatalogIdDataServiceDataServiceIdRoute
  '/catalog/$catalogId/dataset/$datasetId': typeof CatalogCatalogIdDatasetDatasetIdRoute
  '/catalog/$catalogId/distribution-connector/$distributionId': typeof CatalogCatalogIdDistributionConnectorDistributionIdRoute
  '/transfer-process/$transferProcessId/transfer-message/$transferMessageId': typeof TransferProcessTransferProcessIdTransferMessageTransferMessageIdRoute
  '/catalog/participant/$participantId/': typeof CatalogParticipantParticipantIdIndexRoute
  '/catalog/participant/$participantId/dataset/$datasetId': typeof CatalogParticipantParticipantIdDatasetDatasetIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agreements'
    | '/authority'
    | '/catalog'
    | '/connections'
    | '/contract-negotiation'
    | '/events'
    | '/keystore'
    | '/my-catalog'
    | '/oauth'
    | '/participants'
    | '/subscriptions'
    | '/transfer-process'
    | '/wallet'
    | '/catalog/$catalogId'
    | '/catalog/participant'
    | '/connections/received'
    | '/connections/sent'
    | '/contract-negotiation/$cnProcess'
    | '/participants/$participantId'
    | '/transfer-process/$transferProcessId'
    | '/agreements/$agreementId'
    | '/authority/new'
    | '/authority/request-details'
    | '/events/dlq'
    | '/events/feed'
    | '/events/subscriptions'
    | '/keystore/config'
    | '/keystore/parameters'
    | '/keystore/secrets'
    | '/my-catalog/new'
    | '/oauth/clients'
    | '/oauth/pats'
    | '/wallet/credentials'
    | '/wallet/did'
    | '/wallet/info'
    | '/wallet/keys'
    | '/wallet/oidc4vci'
    | '/wallet/oidc4vp'
    | '/agreements/'
    | '/authority/'
    | '/catalog/'
    | '/connections/'
    | '/contract-negotiation/'
    | '/events/'
    | '/keystore/'
    | '/login'
    | '/my-catalog/'
    | '/oauth/'
    | '/participants/'
    | '/subscriptions/'
    | '/transfer-process/'
    | '/wallet/'
    | '/connections/received/request-details'
    | '/connections/sent/new'
    | '/connections/sent/request-details'
    | '/catalog/$catalogId/'
    | '/connections/received/'
    | '/connections/sent/'
    | '/contract-negotiation/$cnProcess/'
    | '/participants/$participantId/'
    | '/transfer-process/$transferProcessId/'
    | '/catalog/$catalogId/data-service/$dataServiceId'
    | '/catalog/$catalogId/dataset/$datasetId'
    | '/catalog/$catalogId/distribution-connector/$distributionId'
    | '/transfer-process/$transferProcessId/transfer-message/$transferMessageId'
    | '/catalog/participant/$participantId'
    | '/catalog/participant/$participantId/dataset/$datasetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog/participant'
    | '/agreements/$agreementId'
    | '/authority/new'
    | '/authority/request-details'
    | '/events/dlq'
    | '/events/feed'
    | '/events/subscriptions'
    | '/keystore/config'
    | '/keystore/parameters'
    | '/keystore/secrets'
    | '/my-catalog/new'
    | '/oauth/clients'
    | '/oauth/pats'
    | '/wallet/credentials'
    | '/wallet/did'
    | '/wallet/info'
    | '/wallet/keys'
    | '/wallet/oidc4vci'
    | '/wallet/oidc4vp'
    | '/agreements'
    | '/authority'
    | '/catalog'
    | '/connections'
    | '/contract-negotiation'
    | '/events'
    | '/keystore'
    | '/login'
    | '/my-catalog'
    | '/oauth'
    | '/participants'
    | '/subscriptions'
    | '/transfer-process'
    | '/wallet'
    | '/connections/received/request-details'
    | '/connections/sent/new'
    | '/connections/sent/request-details'
    | '/catalog/$catalogId'
    | '/connections/received'
    | '/connections/sent'
    | '/contract-negotiation/$cnProcess'
    | '/participants/$participantId'
    | '/transfer-process/$transferProcessId'
    | '/catalog/$catalogId/data-service/$dataServiceId'
    | '/catalog/$catalogId/dataset/$datasetId'
    | '/catalog/$catalogId/distribution-connector/$distributionId'
    | '/transfer-process/$transferProcessId/transfer-message/$transferMessageId'
    | '/catalog/participant/$participantId'
    | '/catalog/participant/$participantId/dataset/$datasetId'
  id:
    | '__root__'
    | '/'
    | '/agreements'
    | '/authority'
    | '/catalog'
    | '/connections'
    | '/contract-negotiation'
    | '/events'
    | '/keystore'
    | '/my-catalog'
    | '/oauth'
    | '/participants'
    | '/subscriptions'
    | '/transfer-process'
    | '/wallet'
    | '/catalog/$catalogId'
    | '/catalog/participant'
    | '/connections/received'
    | '/connections/sent'
    | '/contract-negotiation/$cnProcess'
    | '/participants/$participantId'
    | '/transfer-process/$transferProcessId'
    | '/agreements/$agreementId'
    | '/authority/new'
    | '/authority/request-details'
    | '/events/dlq'
    | '/events/feed'
    | '/events/subscriptions'
    | '/keystore/config'
    | '/keystore/parameters'
    | '/keystore/secrets'
    | '/my-catalog/new'
    | '/oauth/clients'
    | '/oauth/pats'
    | '/wallet/credentials'
    | '/wallet/did'
    | '/wallet/info'
    | '/wallet/keys'
    | '/wallet/oidc4vci'
    | '/wallet/oidc4vp'
    | '/agreements/'
    | '/authority/'
    | '/catalog/'
    | '/connections/'
    | '/contract-negotiation/'
    | '/events/'
    | '/keystore/'
    | '/login/'
    | '/my-catalog/'
    | '/oauth/'
    | '/participants/'
    | '/subscriptions/'
    | '/transfer-process/'
    | '/wallet/'
    | '/connections/received/request-details'
    | '/connections/sent/new'
    | '/connections/sent/request-details'
    | '/catalog/$catalogId/'
    | '/connections/received/'
    | '/connections/sent/'
    | '/contract-negotiation/$cnProcess/'
    | '/participants/$participantId/'
    | '/transfer-process/$transferProcessId/'
    | '/catalog/$catalogId/data-service/$dataServiceId'
    | '/catalog/$catalogId/dataset/$datasetId'
    | '/catalog/$catalogId/distribution-connector/$distributionId'
    | '/transfer-process/$transferProcessId/transfer-message/$transferMessageId'
    | '/catalog/participant/$participantId/'
    | '/catalog/participant/$participantId/dataset/$datasetId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgreementsRouteRoute: typeof AgreementsRouteRouteWithChildren
  AuthorityRouteRoute: typeof AuthorityRouteRouteWithChildren
  CatalogRouteRoute: typeof CatalogRouteRouteWithChildren
  ConnectionsRouteRoute: typeof ConnectionsRouteRouteWithChildren
  ContractNegotiationRouteRoute: typeof ContractNegotiationRouteRouteWithChildren
  EventsRouteRoute: typeof EventsRouteRouteWithChildren
  KeystoreRouteRoute: typeof KeystoreRouteRouteWithChildren
  MyCatalogRouteRoute: typeof MyCatalogRouteRouteWithChildren
  OauthRouteRoute: typeof OauthRouteRouteWithChildren
  ParticipantsRouteRoute: typeof ParticipantsRouteRouteWithChildren
  SubscriptionsRouteRoute: typeof SubscriptionsRouteRouteWithChildren
  TransferProcessRouteRoute: typeof TransferProcessRouteRouteWithChildren
  WalletRouteRoute: typeof WalletRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgreementsRouteRoute: AgreementsRouteRouteWithChildren,
  AuthorityRouteRoute: AuthorityRouteRouteWithChildren,
  CatalogRouteRoute: CatalogRouteRouteWithChildren,
  ConnectionsRouteRoute: ConnectionsRouteRouteWithChildren,
  ContractNegotiationRouteRoute: ContractNegotiationRouteRouteWithChildren,
  EventsRouteRoute: EventsRouteRouteWithChildren,
  KeystoreRouteRoute: KeystoreRouteRouteWithChildren,
  MyCatalogRouteRoute: MyCatalogRouteRouteWithChildren,
  OauthRouteRoute: OauthRouteRouteWithChildren,
  ParticipantsRouteRoute: ParticipantsRouteRouteWithChildren,
  SubscriptionsRouteRoute: SubscriptionsRouteRouteWithChildren,
  TransferProcessRouteRoute: TransferProcessRouteRouteWithChildren,
  WalletRouteRoute: WalletRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/agreements",
        "/authority",
        "/catalog",
        "/connections",
        "/contract-negotiation",
        "/events",
        "/keystore",
        "/my-catalog",
        "/oauth",
        "/participants",
        "/subscriptions",
        "/transfer-process",
        "/wallet",
        "/login/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/agreements": {
      "filePath": "agreements/route.tsx",
      "children": [
        "/agreements/$agreementId",
        "/agreements/"
      ]
    },
    "/authority": {
      "filePath": "authority/route.tsx",
      "children": [
        "/authority/new",
        "/authority/request-details",
        "/authority/"
      ]
    },
    "/catalog": {
      "filePath": "catalog/route.tsx",
      "children": [
        "/catalog/$catalogId",
        "/catalog/participant",
        "/catalog/"
      ]
    },
    "/connections": {
      "filePath": "connections/route.tsx",
      "children": [
        "/connections/received",
        "/connections/sent",
        "/connections/"
      ]
    },
    "/contract-negotiation": {
      "filePath": "contract-negotiation/route.tsx",
      "children": [
        "/contract-negotiation/$cnProcess",
        "/contract-negotiation/"
      ]
    },
    "/events": {
      "filePath": "events/route.tsx",
      "children": [
        "/events/dlq",
        "/events/feed",
        "/events/subscriptions",
        "/events/"
      ]
    },
    "/keystore": {
      "filePath": "keystore/route.tsx",
      "children": [
        "/keystore/config",
        "/keystore/parameters",
        "/keystore/secrets",
        "/keystore/"
      ]
    },
    "/my-catalog": {
      "filePath": "my-catalog/route.tsx",
      "children": [
        "/my-catalog/new",
        "/my-catalog/"
      ]
    },
    "/oauth": {
      "filePath": "oauth/route.tsx",
      "children": [
        "/oauth/clients",
        "/oauth/pats",
        "/oauth/"
      ]
    },
    "/participants": {
      "filePath": "participants/route.tsx",
      "children": [
        "/participants/$participantId",
        "/participants/"
      ]
    },
    "/subscriptions": {
      "filePath": "subscriptions/route.tsx",
      "children": [
        "/subscriptions/"
      ]
    },
    "/transfer-process": {
      "filePath": "transfer-process/route.tsx",
      "children": [
        "/transfer-process/$transferProcessId",
        "/transfer-process/"
      ]
    },
    "/wallet": {
      "filePath": "wallet/route.tsx",
      "children": [
        "/wallet/credentials",
        "/wallet/did",
        "/wallet/info",
        "/wallet/keys",
        "/wallet/oidc4vci",
        "/wallet/oidc4vp",
        "/wallet/"
      ]
    },
    "/catalog/$catalogId": {
      "filePath": "catalog/$catalogId/route.tsx",
      "parent": "/catalog",
      "children": [
        "/catalog/$catalogId/",
        "/catalog/$catalogId/data-service/$dataServiceId",
        "/catalog/$catalogId/dataset/$datasetId",
        "/catalog/$catalogId/distribution-connector/$distributionId"
      ]
    },
    "/catalog/participant": {
      "filePath": "catalog/participant/route.tsx",
      "parent": "/catalog",
      "children": [
        "/catalog/participant/$participantId/",
        "/catalog/participant/$participantId/dataset/$datasetId"
      ]
    },
    "/connections/received": {
      "filePath": "connections/received/route.tsx",
      "parent": "/connections",
      "children": [
        "/connections/received/request-details",
        "/connections/received/"
      ]
    },
    "/connections/sent": {
      "filePath": "connections/sent/route.tsx",
      "parent": "/connections",
      "children": [
        "/connections/sent/new",
        "/connections/sent/request-details",
        "/connections/sent/"
      ]
    },
    "/contract-negotiation/$cnProcess": {
      "filePath": "contract-negotiation/$cnProcess/route.tsx",
      "parent": "/contract-negotiation",
      "children": [
        "/contract-negotiation/$cnProcess/"
      ]
    },
    "/participants/$participantId": {
      "filePath": "participants/$participantId/route.tsx",
      "parent": "/participants",
      "children": [
        "/participants/$participantId/"
      ]
    },
    "/transfer-process/$transferProcessId": {
      "filePath": "transfer-process/$transferProcessId/route.tsx",
      "parent": "/transfer-process",
      "children": [
        "/transfer-process/$transferProcessId/",
        "/transfer-process/$transferProcessId/transfer-message/$transferMessageId"
      ]
    },
    "/agreements/$agreementId": {
      "filePath": "agreements/$agreementId.tsx",
      "parent": "/agreements"
    },
    "/authority/new": {
      "filePath": "authority/new.tsx",
      "parent": "/authority"
    },
    "/authority/request-details": {
      "filePath": "authority/request-details.tsx",
      "parent": "/authority"
    },
    "/events/dlq": {
      "filePath": "events/dlq.tsx",
      "parent": "/events"
    },
    "/events/feed": {
      "filePath": "events/feed.tsx",
      "parent": "/events"
    },
    "/events/subscriptions": {
      "filePath": "events/subscriptions.tsx",
      "parent": "/events"
    },
    "/keystore/config": {
      "filePath": "keystore/config.tsx",
      "parent": "/keystore"
    },
    "/keystore/parameters": {
      "filePath": "keystore/parameters.tsx",
      "parent": "/keystore"
    },
    "/keystore/secrets": {
      "filePath": "keystore/secrets.tsx",
      "parent": "/keystore"
    },
    "/my-catalog/new": {
      "filePath": "my-catalog/new.tsx",
      "parent": "/my-catalog"
    },
    "/oauth/clients": {
      "filePath": "oauth/clients.tsx",
      "parent": "/oauth"
    },
    "/oauth/pats": {
      "filePath": "oauth/pats.tsx",
      "parent": "/oauth"
    },
    "/wallet/credentials": {
      "filePath": "wallet/credentials.tsx",
      "parent": "/wallet"
    },
    "/wallet/did": {
      "filePath": "wallet/did.tsx",
      "parent": "/wallet"
    },
    "/wallet/info": {
      "filePath": "wallet/info.tsx",
      "parent": "/wallet"
    },
    "/wallet/keys": {
      "filePath": "wallet/keys.tsx",
      "parent": "/wallet"
    },
    "/wallet/oidc4vci": {
      "filePath": "wallet/oidc4vci.tsx",
      "parent": "/wallet"
    },
    "/wallet/oidc4vp": {
      "filePath": "wallet/oidc4vp.tsx",
      "parent": "/wallet"
    },
    "/agreements/": {
      "filePath": "agreements/index.tsx",
      "parent": "/agreements"
    },
    "/authority/": {
      "filePath": "authority/index.tsx",
      "parent": "/authority"
    },
    "/catalog/": {
      "filePath": "catalog/index.tsx",
      "parent": "/catalog"
    },
    "/connections/": {
      "filePath": "connections/index.tsx",
      "parent": "/connections"
    },
    "/contract-negotiation/": {
      "filePath": "contract-negotiation/index.tsx",
      "parent": "/contract-negotiation"
    },
    "/events/": {
      "filePath": "events/index.tsx",
      "parent": "/events"
    },
    "/keystore/": {
      "filePath": "keystore/index.tsx",
      "parent": "/keystore"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/my-catalog/": {
      "filePath": "my-catalog/index.tsx",
      "parent": "/my-catalog"
    },
    "/oauth/": {
      "filePath": "oauth/index.tsx",
      "parent": "/oauth"
    },
    "/participants/": {
      "filePath": "participants/index.tsx",
      "parent": "/participants"
    },
    "/subscriptions/": {
      "filePath": "subscriptions/index.tsx",
      "parent": "/subscriptions"
    },
    "/transfer-process/": {
      "filePath": "transfer-process/index.tsx",
      "parent": "/transfer-process"
    },
    "/wallet/": {
      "filePath": "wallet/index.tsx",
      "parent": "/wallet"
    },
    "/connections/received/request-details": {
      "filePath": "connections/received/request-details.tsx",
      "parent": "/connections/received"
    },
    "/connections/sent/new": {
      "filePath": "connections/sent/new.tsx",
      "parent": "/connections/sent"
    },
    "/connections/sent/request-details": {
      "filePath": "connections/sent/request-details.tsx",
      "parent": "/connections/sent"
    },
    "/catalog/$catalogId/": {
      "filePath": "catalog/$catalogId/index.tsx",
      "parent": "/catalog/$catalogId"
    },
    "/connections/received/": {
      "filePath": "connections/received/index.tsx",
      "parent": "/connections/received"
    },
    "/connections/sent/": {
      "filePath": "connections/sent/index.tsx",
      "parent": "/connections/sent"
    },
    "/contract-negotiation/$cnProcess/": {
      "filePath": "contract-negotiation/$cnProcess/index.tsx",
      "parent": "/contract-negotiation/$cnProcess"
    },
    "/participants/$participantId/": {
      "filePath": "participants/$participantId/index.tsx",
      "parent": "/participants/$participantId"
    },
    "/transfer-process/$transferProcessId/": {
      "filePath": "transfer-process/$transferProcessId/index.tsx",
      "parent": "/transfer-process/$transferProcessId"
    },
    "/catalog/$catalogId/data-service/$dataServiceId": {
      "filePath": "catalog/$catalogId/data-service.$dataServiceId.tsx",
      "parent": "/catalog/$catalogId"
    },
    "/catalog/$catalogId/dataset/$datasetId": {
      "filePath": "catalog/$catalogId/dataset.$datasetId.tsx",
      "parent": "/catalog/$catalogId"
    },
    "/catalog/$catalogId/distribution-connector/$distributionId": {
      "filePath": "catalog/$catalogId/distribution-connector.$distributionId.tsx",
      "parent": "/catalog/$catalogId"
    },
    "/transfer-process/$transferProcessId/transfer-message/$transferMessageId": {
      "filePath": "transfer-process/$transferProcessId/transfer-message.$transferMessageId.tsx",
      "parent": "/transfer-process/$transferProcessId"
    },
    "/catalog/participant/$participantId/": {
      "filePath": "catalog/participant/$participantId/index.tsx",
      "parent": "/catalog/participant"
    },
    "/catalog/participant/$participantId/dataset/$datasetId": {
      "filePath": "catalog/participant/$participantId/dataset.$datasetId.tsx",
      "parent": "/catalog/participant"
    }
  }
}
ROUTE_MANIFEST_END */
