/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * OpenAPI specification for the Eunomia DS-Agent Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  CreateSubscriptionCommand,
  DeadLetterRecord,
  EventDeliveryRecord,
  EventEnvelope,
  EventSubscription,
  InternalServerErrorResponse,
  ListDeadLettersParams,
  ListEventsFeedParams,
  NotFoundResponse,
  PublishEventCommand,
  ReplayAllResponse,
  StreamEventsSseParams,
  UpdateSubscriptionCommand
} from '.././model';

import { customInstance } from '../../orval-mutator';
import type { ErrorType , BodyType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List events feed
 */
export type listEventsFeedResponse200 = {
  data: EventEnvelope[]
  status: 200
}

export type listEventsFeedResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type listEventsFeedResponseSuccess = (listEventsFeedResponse200) & {
  headers: Headers;
};
export type listEventsFeedResponseError = (listEventsFeedResponse500) & {
  headers: Headers;
};

export type listEventsFeedResponse = (listEventsFeedResponseSuccess | listEventsFeedResponseError)

export const getListEventsFeedUrl = (params?: ListEventsFeedParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/events?${stringifiedParams}` : `/events`
}

export const listEventsFeed = async (params?: ListEventsFeedParams, options?: RequestInit): Promise<listEventsFeedResponse> => {
  
  return customInstance<listEventsFeedResponse>(getListEventsFeedUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListEventsFeedInfiniteQueryKey = (params?: ListEventsFeedParams,) => {
    return [
    'infinite', `/events`, ...(params ? [params] : [])
    ] as const;
    }

export const getListEventsFeedQueryKey = (params?: ListEventsFeedParams,) => {
    return [
    `/events`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListEventsFeedInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof listEventsFeed>>>, TError = ErrorType<InternalServerErrorResponse>>(params?: ListEventsFeedParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listEventsFeed>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEventsFeedInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEventsFeed>>> = ({ signal }) => listEventsFeed(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof listEventsFeed>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListEventsFeedInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof listEventsFeed>>>
export type ListEventsFeedInfiniteQueryError = ErrorType<InternalServerErrorResponse>


export function useListEventsFeedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listEventsFeed>>>, TError = ErrorType<InternalServerErrorResponse>>(
 params: undefined |  ListEventsFeedParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listEventsFeed>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEventsFeed>>,
          TError,
          Awaited<ReturnType<typeof listEventsFeed>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListEventsFeedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listEventsFeed>>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: ListEventsFeedParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listEventsFeed>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEventsFeed>>,
          TError,
          Awaited<ReturnType<typeof listEventsFeed>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListEventsFeedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listEventsFeed>>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: ListEventsFeedParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listEventsFeed>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List events feed
 */

export function useListEventsFeedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listEventsFeed>>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: ListEventsFeedParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listEventsFeed>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListEventsFeedInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getListEventsFeedQueryOptions = <TData = Awaited<ReturnType<typeof listEventsFeed>>, TError = ErrorType<InternalServerErrorResponse>>(params?: ListEventsFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEventsFeed>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEventsFeedQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEventsFeed>>> = ({ signal }) => listEventsFeed(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEventsFeed>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListEventsFeedQueryResult = NonNullable<Awaited<ReturnType<typeof listEventsFeed>>>
export type ListEventsFeedQueryError = ErrorType<InternalServerErrorResponse>


export function useListEventsFeed<TData = Awaited<ReturnType<typeof listEventsFeed>>, TError = ErrorType<InternalServerErrorResponse>>(
 params: undefined |  ListEventsFeedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEventsFeed>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEventsFeed>>,
          TError,
          Awaited<ReturnType<typeof listEventsFeed>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListEventsFeed<TData = Awaited<ReturnType<typeof listEventsFeed>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: ListEventsFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEventsFeed>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEventsFeed>>,
          TError,
          Awaited<ReturnType<typeof listEventsFeed>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListEventsFeed<TData = Awaited<ReturnType<typeof listEventsFeed>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: ListEventsFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEventsFeed>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List events feed
 */

export function useListEventsFeed<TData = Awaited<ReturnType<typeof listEventsFeed>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: ListEventsFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEventsFeed>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListEventsFeedQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Publish event
 */
export type publishEventResponse201 = {
  data: EventEnvelope
  status: 201
}

export type publishEventResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type publishEventResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type publishEventResponseSuccess = (publishEventResponse201) & {
  headers: Headers;
};
export type publishEventResponseError = (publishEventResponse400 | publishEventResponse500) & {
  headers: Headers;
};

export type publishEventResponse = (publishEventResponseSuccess | publishEventResponseError)

export const getPublishEventUrl = () => {


  

  return `/events`
}

export const publishEvent = async (publishEventCommand: PublishEventCommand, options?: RequestInit): Promise<publishEventResponse> => {
  
  return customInstance<publishEventResponse>(getPublishEventUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      publishEventCommand,)
  }
);}




export const getPublishEventMutationOptions = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishEvent>>, TError,{data: BodyType<PublishEventCommand>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof publishEvent>>, TError,{data: BodyType<PublishEventCommand>}, TContext> => {

const mutationKey = ['publishEvent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof publishEvent>>, {data: BodyType<PublishEventCommand>}> = (props) => {
          const {data} = props ?? {};

          return  publishEvent(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PublishEventMutationResult = NonNullable<Awaited<ReturnType<typeof publishEvent>>>
    export type PublishEventMutationBody = BodyType<PublishEventCommand>
    export type PublishEventMutationError = ErrorType<BadRequestResponse | InternalServerErrorResponse>

    /**
 * @summary Publish event
 */
export const usePublishEvent = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishEvent>>, TError,{data: BodyType<PublishEventCommand>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof publishEvent>>,
        TError,
        {data: BodyType<PublishEventCommand>},
        TContext
      > => {
      return useMutation(getPublishEventMutationOptions(options), queryClient);
    }
    /**
 * @summary Get event by ID
 */
export type getEventByIdResponse200 = {
  data: EventEnvelope
  status: 200
}

export type getEventByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getEventByIdResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type getEventByIdResponseSuccess = (getEventByIdResponse200) & {
  headers: Headers;
};
export type getEventByIdResponseError = (getEventByIdResponse404 | getEventByIdResponse500) & {
  headers: Headers;
};

export type getEventByIdResponse = (getEventByIdResponseSuccess | getEventByIdResponseError)

export const getGetEventByIdUrl = (eventId: string,) => {


  

  return `/events/${eventId}`
}

export const getEventById = async (eventId: string, options?: RequestInit): Promise<getEventByIdResponse> => {
  
  return customInstance<getEventByIdResponse>(getGetEventByIdUrl(eventId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetEventByIdInfiniteQueryKey = (eventId: string,) => {
    return [
    'infinite', `/events/${eventId}`
    ] as const;
    }

export const getGetEventByIdQueryKey = (eventId: string,) => {
    return [
    `/events/${eventId}`
    ] as const;
    }

    
export const getGetEventByIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getEventById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(eventId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEventByIdInfiniteQueryKey(eventId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEventById>>> = ({ signal }) => getEventById(eventId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(eventId),  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetEventByIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getEventById>>>
export type GetEventByIdInfiniteQueryError = ErrorType<NotFoundResponse | InternalServerErrorResponse>


export function useGetEventByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getEventById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 eventId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventById>>,
          TError,
          Awaited<ReturnType<typeof getEventById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetEventByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getEventById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 eventId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventById>>,
          TError,
          Awaited<ReturnType<typeof getEventById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetEventByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getEventById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 eventId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get event by ID
 */

export function useGetEventByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getEventById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 eventId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetEventByIdInfiniteQueryOptions(eventId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetEventByIdQueryOptions = <TData = Awaited<ReturnType<typeof getEventById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(eventId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEventByIdQueryKey(eventId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEventById>>> = ({ signal }) => getEventById(eventId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(eventId),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetEventByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getEventById>>>
export type GetEventByIdQueryError = ErrorType<NotFoundResponse | InternalServerErrorResponse>


export function useGetEventById<TData = Awaited<ReturnType<typeof getEventById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 eventId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventById>>,
          TError,
          Awaited<ReturnType<typeof getEventById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetEventById<TData = Awaited<ReturnType<typeof getEventById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 eventId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventById>>,
          TError,
          Awaited<ReturnType<typeof getEventById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetEventById<TData = Awaited<ReturnType<typeof getEventById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 eventId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get event by ID
 */

export function useGetEventById<TData = Awaited<ReturnType<typeof getEventById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 eventId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetEventByIdQueryOptions(eventId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Stream events via Server-Sent Events
 */
export type streamEventsSseResponse200 = {
  data: string
  status: 200
}

export type streamEventsSseResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type streamEventsSseResponseSuccess = (streamEventsSseResponse200) & {
  headers: Headers;
};
export type streamEventsSseResponseError = (streamEventsSseResponse500) & {
  headers: Headers;
};

export type streamEventsSseResponse = (streamEventsSseResponseSuccess | streamEventsSseResponseError)

export const getStreamEventsSseUrl = (params?: StreamEventsSseParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/events/stream?${stringifiedParams}` : `/events/stream`
}

export const streamEventsSse = async (params?: StreamEventsSseParams, options?: RequestInit): Promise<streamEventsSseResponse> => {
  
  return customInstance<streamEventsSseResponse>(getStreamEventsSseUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getStreamEventsSseInfiniteQueryKey = (params?: StreamEventsSseParams,) => {
    return [
    'infinite', `/events/stream`, ...(params ? [params] : [])
    ] as const;
    }

export const getStreamEventsSseQueryKey = (params?: StreamEventsSseParams,) => {
    return [
    `/events/stream`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getStreamEventsSseInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof streamEventsSse>>>, TError = ErrorType<InternalServerErrorResponse>>(params?: StreamEventsSseParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof streamEventsSse>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStreamEventsSseInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof streamEventsSse>>> = ({ signal }) => streamEventsSse(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof streamEventsSse>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type StreamEventsSseInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof streamEventsSse>>>
export type StreamEventsSseInfiniteQueryError = ErrorType<InternalServerErrorResponse>


export function useStreamEventsSseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof streamEventsSse>>>, TError = ErrorType<InternalServerErrorResponse>>(
 params: undefined |  StreamEventsSseParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof streamEventsSse>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamEventsSse>>,
          TError,
          Awaited<ReturnType<typeof streamEventsSse>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useStreamEventsSseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof streamEventsSse>>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: StreamEventsSseParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof streamEventsSse>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamEventsSse>>,
          TError,
          Awaited<ReturnType<typeof streamEventsSse>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useStreamEventsSseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof streamEventsSse>>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: StreamEventsSseParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof streamEventsSse>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Stream events via Server-Sent Events
 */

export function useStreamEventsSseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof streamEventsSse>>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: StreamEventsSseParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof streamEventsSse>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getStreamEventsSseInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getStreamEventsSseQueryOptions = <TData = Awaited<ReturnType<typeof streamEventsSse>>, TError = ErrorType<InternalServerErrorResponse>>(params?: StreamEventsSseParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamEventsSse>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStreamEventsSseQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof streamEventsSse>>> = ({ signal }) => streamEventsSse(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof streamEventsSse>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type StreamEventsSseQueryResult = NonNullable<Awaited<ReturnType<typeof streamEventsSse>>>
export type StreamEventsSseQueryError = ErrorType<InternalServerErrorResponse>


export function useStreamEventsSse<TData = Awaited<ReturnType<typeof streamEventsSse>>, TError = ErrorType<InternalServerErrorResponse>>(
 params: undefined |  StreamEventsSseParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamEventsSse>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamEventsSse>>,
          TError,
          Awaited<ReturnType<typeof streamEventsSse>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useStreamEventsSse<TData = Awaited<ReturnType<typeof streamEventsSse>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: StreamEventsSseParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamEventsSse>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamEventsSse>>,
          TError,
          Awaited<ReturnType<typeof streamEventsSse>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useStreamEventsSse<TData = Awaited<ReturnType<typeof streamEventsSse>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: StreamEventsSseParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamEventsSse>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Stream events via Server-Sent Events
 */

export function useStreamEventsSse<TData = Awaited<ReturnType<typeof streamEventsSse>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: StreamEventsSseParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof streamEventsSse>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getStreamEventsSseQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List event subscriptions
 */
export type listEventSubscriptionsResponse200 = {
  data: EventSubscription[]
  status: 200
}

export type listEventSubscriptionsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type listEventSubscriptionsResponseSuccess = (listEventSubscriptionsResponse200) & {
  headers: Headers;
};
export type listEventSubscriptionsResponseError = (listEventSubscriptionsResponse500) & {
  headers: Headers;
};

export type listEventSubscriptionsResponse = (listEventSubscriptionsResponseSuccess | listEventSubscriptionsResponseError)

export const getListEventSubscriptionsUrl = () => {


  

  return `/events/subscriptions`
}

export const listEventSubscriptions = async ( options?: RequestInit): Promise<listEventSubscriptionsResponse> => {
  
  return customInstance<listEventSubscriptionsResponse>(getListEventSubscriptionsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListEventSubscriptionsInfiniteQueryKey = () => {
    return [
    'infinite', `/events/subscriptions`
    ] as const;
    }

export const getListEventSubscriptionsQueryKey = () => {
    return [
    `/events/subscriptions`
    ] as const;
    }

    
export const getListEventSubscriptionsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof listEventSubscriptions>>>, TError = ErrorType<InternalServerErrorResponse>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEventSubscriptionsInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEventSubscriptions>>> = ({ signal }) => listEventSubscriptions({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListEventSubscriptionsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof listEventSubscriptions>>>
export type ListEventSubscriptionsInfiniteQueryError = ErrorType<InternalServerErrorResponse>


export function useListEventSubscriptionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listEventSubscriptions>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEventSubscriptions>>,
          TError,
          Awaited<ReturnType<typeof listEventSubscriptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListEventSubscriptionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listEventSubscriptions>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEventSubscriptions>>,
          TError,
          Awaited<ReturnType<typeof listEventSubscriptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListEventSubscriptionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listEventSubscriptions>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List event subscriptions
 */

export function useListEventSubscriptionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listEventSubscriptions>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListEventSubscriptionsInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getListEventSubscriptionsQueryOptions = <TData = Awaited<ReturnType<typeof listEventSubscriptions>>, TError = ErrorType<InternalServerErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEventSubscriptionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEventSubscriptions>>> = ({ signal }) => listEventSubscriptions({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListEventSubscriptionsQueryResult = NonNullable<Awaited<ReturnType<typeof listEventSubscriptions>>>
export type ListEventSubscriptionsQueryError = ErrorType<InternalServerErrorResponse>


export function useListEventSubscriptions<TData = Awaited<ReturnType<typeof listEventSubscriptions>>, TError = ErrorType<InternalServerErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEventSubscriptions>>,
          TError,
          Awaited<ReturnType<typeof listEventSubscriptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListEventSubscriptions<TData = Awaited<ReturnType<typeof listEventSubscriptions>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEventSubscriptions>>,
          TError,
          Awaited<ReturnType<typeof listEventSubscriptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListEventSubscriptions<TData = Awaited<ReturnType<typeof listEventSubscriptions>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List event subscriptions
 */

export function useListEventSubscriptions<TData = Awaited<ReturnType<typeof listEventSubscriptions>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEventSubscriptions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListEventSubscriptionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create event subscription
 */
export type createEventSubscriptionResponse201 = {
  data: EventSubscription
  status: 201
}

export type createEventSubscriptionResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createEventSubscriptionResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type createEventSubscriptionResponseSuccess = (createEventSubscriptionResponse201) & {
  headers: Headers;
};
export type createEventSubscriptionResponseError = (createEventSubscriptionResponse400 | createEventSubscriptionResponse500) & {
  headers: Headers;
};

export type createEventSubscriptionResponse = (createEventSubscriptionResponseSuccess | createEventSubscriptionResponseError)

export const getCreateEventSubscriptionUrl = () => {


  

  return `/events/subscriptions`
}

export const createEventSubscription = async (createSubscriptionCommand: CreateSubscriptionCommand, options?: RequestInit): Promise<createEventSubscriptionResponse> => {
  
  return customInstance<createEventSubscriptionResponse>(getCreateEventSubscriptionUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSubscriptionCommand,)
  }
);}




export const getCreateEventSubscriptionMutationOptions = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEventSubscription>>, TError,{data: BodyType<CreateSubscriptionCommand>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createEventSubscription>>, TError,{data: BodyType<CreateSubscriptionCommand>}, TContext> => {

const mutationKey = ['createEventSubscription'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createEventSubscription>>, {data: BodyType<CreateSubscriptionCommand>}> = (props) => {
          const {data} = props ?? {};

          return  createEventSubscription(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateEventSubscriptionMutationResult = NonNullable<Awaited<ReturnType<typeof createEventSubscription>>>
    export type CreateEventSubscriptionMutationBody = BodyType<CreateSubscriptionCommand>
    export type CreateEventSubscriptionMutationError = ErrorType<BadRequestResponse | InternalServerErrorResponse>

    /**
 * @summary Create event subscription
 */
export const useCreateEventSubscription = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEventSubscription>>, TError,{data: BodyType<CreateSubscriptionCommand>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createEventSubscription>>,
        TError,
        {data: BodyType<CreateSubscriptionCommand>},
        TContext
      > => {
      return useMutation(getCreateEventSubscriptionMutationOptions(options), queryClient);
    }
    /**
 * @summary Get event subscription by ID
 */
export type getEventSubscriptionByIdResponse200 = {
  data: EventSubscription
  status: 200
}

export type getEventSubscriptionByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getEventSubscriptionByIdResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type getEventSubscriptionByIdResponseSuccess = (getEventSubscriptionByIdResponse200) & {
  headers: Headers;
};
export type getEventSubscriptionByIdResponseError = (getEventSubscriptionByIdResponse404 | getEventSubscriptionByIdResponse500) & {
  headers: Headers;
};

export type getEventSubscriptionByIdResponse = (getEventSubscriptionByIdResponseSuccess | getEventSubscriptionByIdResponseError)

export const getGetEventSubscriptionByIdUrl = (subscriptionId: string,) => {


  

  return `/events/subscriptions/${subscriptionId}`
}

export const getEventSubscriptionById = async (subscriptionId: string, options?: RequestInit): Promise<getEventSubscriptionByIdResponse> => {
  
  return customInstance<getEventSubscriptionByIdResponse>(getGetEventSubscriptionByIdUrl(subscriptionId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetEventSubscriptionByIdInfiniteQueryKey = (subscriptionId: string,) => {
    return [
    'infinite', `/events/subscriptions/${subscriptionId}`
    ] as const;
    }

export const getGetEventSubscriptionByIdQueryKey = (subscriptionId: string,) => {
    return [
    `/events/subscriptions/${subscriptionId}`
    ] as const;
    }

    
export const getGetEventSubscriptionByIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getEventSubscriptionById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(subscriptionId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getEventSubscriptionById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEventSubscriptionByIdInfiniteQueryKey(subscriptionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEventSubscriptionById>>> = ({ signal }) => getEventSubscriptionById(subscriptionId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(subscriptionId),  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getEventSubscriptionById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetEventSubscriptionByIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getEventSubscriptionById>>>
export type GetEventSubscriptionByIdInfiniteQueryError = ErrorType<NotFoundResponse | InternalServerErrorResponse>


export function useGetEventSubscriptionByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getEventSubscriptionById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 subscriptionId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getEventSubscriptionById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventSubscriptionById>>,
          TError,
          Awaited<ReturnType<typeof getEventSubscriptionById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetEventSubscriptionByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getEventSubscriptionById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 subscriptionId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getEventSubscriptionById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventSubscriptionById>>,
          TError,
          Awaited<ReturnType<typeof getEventSubscriptionById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetEventSubscriptionByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getEventSubscriptionById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 subscriptionId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getEventSubscriptionById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get event subscription by ID
 */

export function useGetEventSubscriptionByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getEventSubscriptionById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 subscriptionId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getEventSubscriptionById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetEventSubscriptionByIdInfiniteQueryOptions(subscriptionId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetEventSubscriptionByIdQueryOptions = <TData = Awaited<ReturnType<typeof getEventSubscriptionById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(subscriptionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventSubscriptionById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEventSubscriptionByIdQueryKey(subscriptionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEventSubscriptionById>>> = ({ signal }) => getEventSubscriptionById(subscriptionId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(subscriptionId),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEventSubscriptionById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetEventSubscriptionByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getEventSubscriptionById>>>
export type GetEventSubscriptionByIdQueryError = ErrorType<NotFoundResponse | InternalServerErrorResponse>


export function useGetEventSubscriptionById<TData = Awaited<ReturnType<typeof getEventSubscriptionById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 subscriptionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventSubscriptionById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventSubscriptionById>>,
          TError,
          Awaited<ReturnType<typeof getEventSubscriptionById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetEventSubscriptionById<TData = Awaited<ReturnType<typeof getEventSubscriptionById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 subscriptionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventSubscriptionById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventSubscriptionById>>,
          TError,
          Awaited<ReturnType<typeof getEventSubscriptionById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetEventSubscriptionById<TData = Awaited<ReturnType<typeof getEventSubscriptionById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 subscriptionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventSubscriptionById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get event subscription by ID
 */

export function useGetEventSubscriptionById<TData = Awaited<ReturnType<typeof getEventSubscriptionById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 subscriptionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventSubscriptionById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetEventSubscriptionByIdQueryOptions(subscriptionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update event subscription
 */
export type updateEventSubscriptionResponse200 = {
  data: EventSubscription
  status: 200
}

export type updateEventSubscriptionResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type updateEventSubscriptionResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type updateEventSubscriptionResponseSuccess = (updateEventSubscriptionResponse200) & {
  headers: Headers;
};
export type updateEventSubscriptionResponseError = (updateEventSubscriptionResponse400 | updateEventSubscriptionResponse500) & {
  headers: Headers;
};

export type updateEventSubscriptionResponse = (updateEventSubscriptionResponseSuccess | updateEventSubscriptionResponseError)

export const getUpdateEventSubscriptionUrl = (subscriptionId: string,) => {


  

  return `/events/subscriptions/${subscriptionId}`
}

export const updateEventSubscription = async (subscriptionId: string,
    updateSubscriptionCommand: UpdateSubscriptionCommand, options?: RequestInit): Promise<updateEventSubscriptionResponse> => {
  
  return customInstance<updateEventSubscriptionResponse>(getUpdateEventSubscriptionUrl(subscriptionId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateSubscriptionCommand,)
  }
);}




export const getUpdateEventSubscriptionMutationOptions = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEventSubscription>>, TError,{subscriptionId: string;data: BodyType<UpdateSubscriptionCommand>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateEventSubscription>>, TError,{subscriptionId: string;data: BodyType<UpdateSubscriptionCommand>}, TContext> => {

const mutationKey = ['updateEventSubscription'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateEventSubscription>>, {subscriptionId: string;data: BodyType<UpdateSubscriptionCommand>}> = (props) => {
          const {subscriptionId,data} = props ?? {};

          return  updateEventSubscription(subscriptionId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateEventSubscriptionMutationResult = NonNullable<Awaited<ReturnType<typeof updateEventSubscription>>>
    export type UpdateEventSubscriptionMutationBody = BodyType<UpdateSubscriptionCommand>
    export type UpdateEventSubscriptionMutationError = ErrorType<BadRequestResponse | InternalServerErrorResponse>

    /**
 * @summary Update event subscription
 */
export const useUpdateEventSubscription = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEventSubscription>>, TError,{subscriptionId: string;data: BodyType<UpdateSubscriptionCommand>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateEventSubscription>>,
        TError,
        {subscriptionId: string;data: BodyType<UpdateSubscriptionCommand>},
        TContext
      > => {
      return useMutation(getUpdateEventSubscriptionMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete event subscription
 */
export type deleteEventSubscriptionResponse204 = {
  data: void
  status: 204
}

export type deleteEventSubscriptionResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteEventSubscriptionResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type deleteEventSubscriptionResponseSuccess = (deleteEventSubscriptionResponse204) & {
  headers: Headers;
};
export type deleteEventSubscriptionResponseError = (deleteEventSubscriptionResponse404 | deleteEventSubscriptionResponse500) & {
  headers: Headers;
};

export type deleteEventSubscriptionResponse = (deleteEventSubscriptionResponseSuccess | deleteEventSubscriptionResponseError)

export const getDeleteEventSubscriptionUrl = (subscriptionId: string,) => {


  

  return `/events/subscriptions/${subscriptionId}`
}

export const deleteEventSubscription = async (subscriptionId: string, options?: RequestInit): Promise<deleteEventSubscriptionResponse> => {
  
  return customInstance<deleteEventSubscriptionResponse>(getDeleteEventSubscriptionUrl(subscriptionId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteEventSubscriptionMutationOptions = <TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEventSubscription>>, TError,{subscriptionId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteEventSubscription>>, TError,{subscriptionId: string}, TContext> => {

const mutationKey = ['deleteEventSubscription'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteEventSubscription>>, {subscriptionId: string}> = (props) => {
          const {subscriptionId} = props ?? {};

          return  deleteEventSubscription(subscriptionId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteEventSubscriptionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEventSubscription>>>
    
    export type DeleteEventSubscriptionMutationError = ErrorType<NotFoundResponse | InternalServerErrorResponse>

    /**
 * @summary Delete event subscription
 */
export const useDeleteEventSubscription = <TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEventSubscription>>, TError,{subscriptionId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteEventSubscription>>,
        TError,
        {subscriptionId: string},
        TContext
      > => {
      return useMutation(getDeleteEventSubscriptionMutationOptions(options), queryClient);
    }
    /**
 * @summary List Dead Letter Queue records
 */
export type listDeadLettersResponse200 = {
  data: DeadLetterRecord[]
  status: 200
}

export type listDeadLettersResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type listDeadLettersResponseSuccess = (listDeadLettersResponse200) & {
  headers: Headers;
};
export type listDeadLettersResponseError = (listDeadLettersResponse500) & {
  headers: Headers;
};

export type listDeadLettersResponse = (listDeadLettersResponseSuccess | listDeadLettersResponseError)

export const getListDeadLettersUrl = (params?: ListDeadLettersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/events/dlq?${stringifiedParams}` : `/events/dlq`
}

export const listDeadLetters = async (params?: ListDeadLettersParams, options?: RequestInit): Promise<listDeadLettersResponse> => {
  
  return customInstance<listDeadLettersResponse>(getListDeadLettersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListDeadLettersInfiniteQueryKey = (params?: ListDeadLettersParams,) => {
    return [
    'infinite', `/events/dlq`, ...(params ? [params] : [])
    ] as const;
    }

export const getListDeadLettersQueryKey = (params?: ListDeadLettersParams,) => {
    return [
    `/events/dlq`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListDeadLettersInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof listDeadLetters>>>, TError = ErrorType<InternalServerErrorResponse>>(params?: ListDeadLettersParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listDeadLetters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDeadLettersInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDeadLetters>>> = ({ signal }) => listDeadLetters(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof listDeadLetters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListDeadLettersInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof listDeadLetters>>>
export type ListDeadLettersInfiniteQueryError = ErrorType<InternalServerErrorResponse>


export function useListDeadLettersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listDeadLetters>>>, TError = ErrorType<InternalServerErrorResponse>>(
 params: undefined |  ListDeadLettersParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listDeadLetters>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDeadLetters>>,
          TError,
          Awaited<ReturnType<typeof listDeadLetters>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListDeadLettersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listDeadLetters>>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: ListDeadLettersParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listDeadLetters>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDeadLetters>>,
          TError,
          Awaited<ReturnType<typeof listDeadLetters>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListDeadLettersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listDeadLetters>>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: ListDeadLettersParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listDeadLetters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List Dead Letter Queue records
 */

export function useListDeadLettersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listDeadLetters>>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: ListDeadLettersParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listDeadLetters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListDeadLettersInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getListDeadLettersQueryOptions = <TData = Awaited<ReturnType<typeof listDeadLetters>>, TError = ErrorType<InternalServerErrorResponse>>(params?: ListDeadLettersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeadLetters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDeadLettersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDeadLetters>>> = ({ signal }) => listDeadLetters(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDeadLetters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListDeadLettersQueryResult = NonNullable<Awaited<ReturnType<typeof listDeadLetters>>>
export type ListDeadLettersQueryError = ErrorType<InternalServerErrorResponse>


export function useListDeadLetters<TData = Awaited<ReturnType<typeof listDeadLetters>>, TError = ErrorType<InternalServerErrorResponse>>(
 params: undefined |  ListDeadLettersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeadLetters>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDeadLetters>>,
          TError,
          Awaited<ReturnType<typeof listDeadLetters>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListDeadLetters<TData = Awaited<ReturnType<typeof listDeadLetters>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: ListDeadLettersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeadLetters>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDeadLetters>>,
          TError,
          Awaited<ReturnType<typeof listDeadLetters>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListDeadLetters<TData = Awaited<ReturnType<typeof listDeadLetters>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: ListDeadLettersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeadLetters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List Dead Letter Queue records
 */

export function useListDeadLetters<TData = Awaited<ReturnType<typeof listDeadLetters>>, TError = ErrorType<InternalServerErrorResponse>>(
 params?: ListDeadLettersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeadLetters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListDeadLettersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Replay all dead letter messages
 */
export type replayAllDeadLettersResponse200 = {
  data: ReplayAllResponse
  status: 200
}

export type replayAllDeadLettersResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type replayAllDeadLettersResponseSuccess = (replayAllDeadLettersResponse200) & {
  headers: Headers;
};
export type replayAllDeadLettersResponseError = (replayAllDeadLettersResponse500) & {
  headers: Headers;
};

export type replayAllDeadLettersResponse = (replayAllDeadLettersResponseSuccess | replayAllDeadLettersResponseError)

export const getReplayAllDeadLettersUrl = () => {


  

  return `/events/dlq/replay-all`
}

export const replayAllDeadLetters = async ( options?: RequestInit): Promise<replayAllDeadLettersResponse> => {
  
  return customInstance<replayAllDeadLettersResponse>(getReplayAllDeadLettersUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getReplayAllDeadLettersMutationOptions = <TError = ErrorType<InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replayAllDeadLetters>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof replayAllDeadLetters>>, TError,void, TContext> => {

const mutationKey = ['replayAllDeadLetters'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof replayAllDeadLetters>>, void> = () => {
          

          return  replayAllDeadLetters(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ReplayAllDeadLettersMutationResult = NonNullable<Awaited<ReturnType<typeof replayAllDeadLetters>>>
    
    export type ReplayAllDeadLettersMutationError = ErrorType<InternalServerErrorResponse>

    /**
 * @summary Replay all dead letter messages
 */
export const useReplayAllDeadLetters = <TError = ErrorType<InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replayAllDeadLetters>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof replayAllDeadLetters>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getReplayAllDeadLettersMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Dead Letter Queue record
 */
export type getDeadLetterByIdResponse200 = {
  data: DeadLetterRecord
  status: 200
}

export type getDeadLetterByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getDeadLetterByIdResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type getDeadLetterByIdResponseSuccess = (getDeadLetterByIdResponse200) & {
  headers: Headers;
};
export type getDeadLetterByIdResponseError = (getDeadLetterByIdResponse404 | getDeadLetterByIdResponse500) & {
  headers: Headers;
};

export type getDeadLetterByIdResponse = (getDeadLetterByIdResponseSuccess | getDeadLetterByIdResponseError)

export const getGetDeadLetterByIdUrl = (dlqId: string,) => {


  

  return `/events/dlq/${dlqId}`
}

export const getDeadLetterById = async (dlqId: string, options?: RequestInit): Promise<getDeadLetterByIdResponse> => {
  
  return customInstance<getDeadLetterByIdResponse>(getGetDeadLetterByIdUrl(dlqId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetDeadLetterByIdInfiniteQueryKey = (dlqId: string,) => {
    return [
    'infinite', `/events/dlq/${dlqId}`
    ] as const;
    }

export const getGetDeadLetterByIdQueryKey = (dlqId: string,) => {
    return [
    `/events/dlq/${dlqId}`
    ] as const;
    }

    
export const getGetDeadLetterByIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getDeadLetterById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(dlqId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDeadLetterById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDeadLetterByIdInfiniteQueryKey(dlqId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDeadLetterById>>> = ({ signal }) => getDeadLetterById(dlqId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(dlqId),  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDeadLetterById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetDeadLetterByIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getDeadLetterById>>>
export type GetDeadLetterByIdInfiniteQueryError = ErrorType<NotFoundResponse | InternalServerErrorResponse>


export function useGetDeadLetterByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getDeadLetterById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 dlqId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDeadLetterById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeadLetterById>>,
          TError,
          Awaited<ReturnType<typeof getDeadLetterById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetDeadLetterByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getDeadLetterById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 dlqId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDeadLetterById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeadLetterById>>,
          TError,
          Awaited<ReturnType<typeof getDeadLetterById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetDeadLetterByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getDeadLetterById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 dlqId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDeadLetterById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Dead Letter Queue record
 */

export function useGetDeadLetterByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getDeadLetterById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 dlqId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDeadLetterById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetDeadLetterByIdInfiniteQueryOptions(dlqId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetDeadLetterByIdQueryOptions = <TData = Awaited<ReturnType<typeof getDeadLetterById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(dlqId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeadLetterById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDeadLetterByIdQueryKey(dlqId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDeadLetterById>>> = ({ signal }) => getDeadLetterById(dlqId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(dlqId),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDeadLetterById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetDeadLetterByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getDeadLetterById>>>
export type GetDeadLetterByIdQueryError = ErrorType<NotFoundResponse | InternalServerErrorResponse>


export function useGetDeadLetterById<TData = Awaited<ReturnType<typeof getDeadLetterById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 dlqId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeadLetterById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeadLetterById>>,
          TError,
          Awaited<ReturnType<typeof getDeadLetterById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetDeadLetterById<TData = Awaited<ReturnType<typeof getDeadLetterById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 dlqId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeadLetterById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeadLetterById>>,
          TError,
          Awaited<ReturnType<typeof getDeadLetterById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetDeadLetterById<TData = Awaited<ReturnType<typeof getDeadLetterById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 dlqId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeadLetterById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Dead Letter Queue record
 */

export function useGetDeadLetterById<TData = Awaited<ReturnType<typeof getDeadLetterById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 dlqId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeadLetterById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetDeadLetterByIdQueryOptions(dlqId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Delete Dead Letter Queue record
 */
export type deleteDeadLetterResponse204 = {
  data: void
  status: 204
}

export type deleteDeadLetterResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteDeadLetterResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type deleteDeadLetterResponseSuccess = (deleteDeadLetterResponse204) & {
  headers: Headers;
};
export type deleteDeadLetterResponseError = (deleteDeadLetterResponse404 | deleteDeadLetterResponse500) & {
  headers: Headers;
};

export type deleteDeadLetterResponse = (deleteDeadLetterResponseSuccess | deleteDeadLetterResponseError)

export const getDeleteDeadLetterUrl = (dlqId: string,) => {


  

  return `/events/dlq/${dlqId}`
}

export const deleteDeadLetter = async (dlqId: string, options?: RequestInit): Promise<deleteDeadLetterResponse> => {
  
  return customInstance<deleteDeadLetterResponse>(getDeleteDeadLetterUrl(dlqId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteDeadLetterMutationOptions = <TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDeadLetter>>, TError,{dlqId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDeadLetter>>, TError,{dlqId: string}, TContext> => {

const mutationKey = ['deleteDeadLetter'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDeadLetter>>, {dlqId: string}> = (props) => {
          const {dlqId} = props ?? {};

          return  deleteDeadLetter(dlqId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDeadLetterMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDeadLetter>>>
    
    export type DeleteDeadLetterMutationError = ErrorType<NotFoundResponse | InternalServerErrorResponse>

    /**
 * @summary Delete Dead Letter Queue record
 */
export const useDeleteDeadLetter = <TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDeadLetter>>, TError,{dlqId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDeadLetter>>,
        TError,
        {dlqId: string},
        TContext
      > => {
      return useMutation(getDeleteDeadLetterMutationOptions(options), queryClient);
    }
    /**
 * @summary Replay a single dead letter message
 */
export type replayDeadLetterResponse200 = {
  data: EventDeliveryRecord
  status: 200
}

export type replayDeadLetterResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type replayDeadLetterResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type replayDeadLetterResponseSuccess = (replayDeadLetterResponse200) & {
  headers: Headers;
};
export type replayDeadLetterResponseError = (replayDeadLetterResponse400 | replayDeadLetterResponse500) & {
  headers: Headers;
};

export type replayDeadLetterResponse = (replayDeadLetterResponseSuccess | replayDeadLetterResponseError)

export const getReplayDeadLetterUrl = (dlqId: string,) => {


  

  return `/events/dlq/${dlqId}/replay`
}

export const replayDeadLetter = async (dlqId: string, options?: RequestInit): Promise<replayDeadLetterResponse> => {
  
  return customInstance<replayDeadLetterResponse>(getReplayDeadLetterUrl(dlqId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getReplayDeadLetterMutationOptions = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replayDeadLetter>>, TError,{dlqId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof replayDeadLetter>>, TError,{dlqId: string}, TContext> => {

const mutationKey = ['replayDeadLetter'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof replayDeadLetter>>, {dlqId: string}> = (props) => {
          const {dlqId} = props ?? {};

          return  replayDeadLetter(dlqId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ReplayDeadLetterMutationResult = NonNullable<Awaited<ReturnType<typeof replayDeadLetter>>>
    
    export type ReplayDeadLetterMutationError = ErrorType<BadRequestResponse | InternalServerErrorResponse>

    /**
 * @summary Replay a single dead letter message
 */
export const useReplayDeadLetter = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replayDeadLetter>>, TError,{dlqId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof replayDeadLetter>>,
        TError,
        {dlqId: string},
        TContext
      > => {
      return useMutation(getReplayDeadLetterMutationOptions(options), queryClient);
    }
    