/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * OpenAPI specification for the Eunomia DS-Agent Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  CreateClientCommand,
  InternalServerErrorResponse,
  NotFoundResponse,
  OAuthClient,
  RotateSecretResponse
} from '.././model';

import { customInstance } from '../../orval-mutator';
import type { ErrorType , BodyType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List registered OAuth clients
 */
export type listOAuthClientsResponse200 = {
  data: OAuthClient[]
  status: 200
}

export type listOAuthClientsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type listOAuthClientsResponseSuccess = (listOAuthClientsResponse200) & {
  headers: Headers;
};
export type listOAuthClientsResponseError = (listOAuthClientsResponse500) & {
  headers: Headers;
};

export type listOAuthClientsResponse = (listOAuthClientsResponseSuccess | listOAuthClientsResponseError)

export const getListOAuthClientsUrl = () => {


  

  return `/oauth/clients`
}

export const listOAuthClients = async ( options?: RequestInit): Promise<listOAuthClientsResponse> => {
  
  return customInstance<listOAuthClientsResponse>(getListOAuthClientsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListOAuthClientsInfiniteQueryKey = () => {
    return [
    'infinite', `/oauth/clients`
    ] as const;
    }

export const getListOAuthClientsQueryKey = () => {
    return [
    `/oauth/clients`
    ] as const;
    }

    
export const getListOAuthClientsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof listOAuthClients>>>, TError = ErrorType<InternalServerErrorResponse>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listOAuthClients>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListOAuthClientsInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listOAuthClients>>> = ({ signal }) => listOAuthClients({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof listOAuthClients>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListOAuthClientsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof listOAuthClients>>>
export type ListOAuthClientsInfiniteQueryError = ErrorType<InternalServerErrorResponse>


export function useListOAuthClientsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listOAuthClients>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listOAuthClients>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOAuthClients>>,
          TError,
          Awaited<ReturnType<typeof listOAuthClients>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListOAuthClientsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listOAuthClients>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listOAuthClients>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOAuthClients>>,
          TError,
          Awaited<ReturnType<typeof listOAuthClients>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListOAuthClientsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listOAuthClients>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listOAuthClients>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List registered OAuth clients
 */

export function useListOAuthClientsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listOAuthClients>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listOAuthClients>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListOAuthClientsInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getListOAuthClientsQueryOptions = <TData = Awaited<ReturnType<typeof listOAuthClients>>, TError = ErrorType<InternalServerErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOAuthClients>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListOAuthClientsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listOAuthClients>>> = ({ signal }) => listOAuthClients({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listOAuthClients>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListOAuthClientsQueryResult = NonNullable<Awaited<ReturnType<typeof listOAuthClients>>>
export type ListOAuthClientsQueryError = ErrorType<InternalServerErrorResponse>


export function useListOAuthClients<TData = Awaited<ReturnType<typeof listOAuthClients>>, TError = ErrorType<InternalServerErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOAuthClients>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOAuthClients>>,
          TError,
          Awaited<ReturnType<typeof listOAuthClients>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListOAuthClients<TData = Awaited<ReturnType<typeof listOAuthClients>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOAuthClients>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOAuthClients>>,
          TError,
          Awaited<ReturnType<typeof listOAuthClients>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListOAuthClients<TData = Awaited<ReturnType<typeof listOAuthClients>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOAuthClients>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List registered OAuth clients
 */

export function useListOAuthClients<TData = Awaited<ReturnType<typeof listOAuthClients>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOAuthClients>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListOAuthClientsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Register OAuth client
 */
export type registerOAuthClientResponse201 = {
  data: RotateSecretResponse
  status: 201
}

export type registerOAuthClientResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type registerOAuthClientResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type registerOAuthClientResponseSuccess = (registerOAuthClientResponse201) & {
  headers: Headers;
};
export type registerOAuthClientResponseError = (registerOAuthClientResponse400 | registerOAuthClientResponse500) & {
  headers: Headers;
};

export type registerOAuthClientResponse = (registerOAuthClientResponseSuccess | registerOAuthClientResponseError)

export const getRegisterOAuthClientUrl = () => {


  

  return `/oauth/clients`
}

export const registerOAuthClient = async (createClientCommand: CreateClientCommand, options?: RequestInit): Promise<registerOAuthClientResponse> => {
  
  return customInstance<registerOAuthClientResponse>(getRegisterOAuthClientUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createClientCommand,)
  }
);}




export const getRegisterOAuthClientMutationOptions = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerOAuthClient>>, TError,{data: BodyType<CreateClientCommand>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof registerOAuthClient>>, TError,{data: BodyType<CreateClientCommand>}, TContext> => {

const mutationKey = ['registerOAuthClient'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerOAuthClient>>, {data: BodyType<CreateClientCommand>}> = (props) => {
          const {data} = props ?? {};

          return  registerOAuthClient(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterOAuthClientMutationResult = NonNullable<Awaited<ReturnType<typeof registerOAuthClient>>>
    export type RegisterOAuthClientMutationBody = BodyType<CreateClientCommand>
    export type RegisterOAuthClientMutationError = ErrorType<BadRequestResponse | InternalServerErrorResponse>

    /**
 * @summary Register OAuth client
 */
export const useRegisterOAuthClient = <TError = ErrorType<BadRequestResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerOAuthClient>>, TError,{data: BodyType<CreateClientCommand>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerOAuthClient>>,
        TError,
        {data: BodyType<CreateClientCommand>},
        TContext
      > => {
      return useMutation(getRegisterOAuthClientMutationOptions(options), queryClient);
    }
    /**
 * @summary Get OAuth client details
 */
export type getOAuthClientByIdResponse200 = {
  data: OAuthClient
  status: 200
}

export type getOAuthClientByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getOAuthClientByIdResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type getOAuthClientByIdResponseSuccess = (getOAuthClientByIdResponse200) & {
  headers: Headers;
};
export type getOAuthClientByIdResponseError = (getOAuthClientByIdResponse404 | getOAuthClientByIdResponse500) & {
  headers: Headers;
};

export type getOAuthClientByIdResponse = (getOAuthClientByIdResponseSuccess | getOAuthClientByIdResponseError)

export const getGetOAuthClientByIdUrl = (clientId: string,) => {


  

  return `/oauth/clients/${clientId}`
}

export const getOAuthClientById = async (clientId: string, options?: RequestInit): Promise<getOAuthClientByIdResponse> => {
  
  return customInstance<getOAuthClientByIdResponse>(getGetOAuthClientByIdUrl(clientId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetOAuthClientByIdInfiniteQueryKey = (clientId: string,) => {
    return [
    'infinite', `/oauth/clients/${clientId}`
    ] as const;
    }

export const getGetOAuthClientByIdQueryKey = (clientId: string,) => {
    return [
    `/oauth/clients/${clientId}`
    ] as const;
    }

    
export const getGetOAuthClientByIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getOAuthClientById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(clientId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthClientById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOAuthClientByIdInfiniteQueryKey(clientId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOAuthClientById>>> = ({ signal }) => getOAuthClientById(clientId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(clientId),  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthClientById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetOAuthClientByIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getOAuthClientById>>>
export type GetOAuthClientByIdInfiniteQueryError = ErrorType<NotFoundResponse | InternalServerErrorResponse>


export function useGetOAuthClientByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getOAuthClientById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 clientId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthClientById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOAuthClientById>>,
          TError,
          Awaited<ReturnType<typeof getOAuthClientById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetOAuthClientByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getOAuthClientById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 clientId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthClientById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOAuthClientById>>,
          TError,
          Awaited<ReturnType<typeof getOAuthClientById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetOAuthClientByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getOAuthClientById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 clientId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthClientById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get OAuth client details
 */

export function useGetOAuthClientByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getOAuthClientById>>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 clientId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getOAuthClientById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetOAuthClientByIdInfiniteQueryOptions(clientId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetOAuthClientByIdQueryOptions = <TData = Awaited<ReturnType<typeof getOAuthClientById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(clientId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuthClientById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOAuthClientByIdQueryKey(clientId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOAuthClientById>>> = ({ signal }) => getOAuthClientById(clientId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(clientId),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOAuthClientById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetOAuthClientByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getOAuthClientById>>>
export type GetOAuthClientByIdQueryError = ErrorType<NotFoundResponse | InternalServerErrorResponse>


export function useGetOAuthClientById<TData = Awaited<ReturnType<typeof getOAuthClientById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 clientId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuthClientById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOAuthClientById>>,
          TError,
          Awaited<ReturnType<typeof getOAuthClientById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetOAuthClientById<TData = Awaited<ReturnType<typeof getOAuthClientById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 clientId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuthClientById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOAuthClientById>>,
          TError,
          Awaited<ReturnType<typeof getOAuthClientById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetOAuthClientById<TData = Awaited<ReturnType<typeof getOAuthClientById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 clientId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuthClientById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get OAuth client details
 */

export function useGetOAuthClientById<TData = Awaited<ReturnType<typeof getOAuthClientById>>, TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>>(
 clientId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuthClientById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetOAuthClientByIdQueryOptions(clientId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Delete OAuth client
 */
export type deleteOAuthClientResponse204 = {
  data: void
  status: 204
}

export type deleteOAuthClientResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteOAuthClientResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type deleteOAuthClientResponseSuccess = (deleteOAuthClientResponse204) & {
  headers: Headers;
};
export type deleteOAuthClientResponseError = (deleteOAuthClientResponse404 | deleteOAuthClientResponse500) & {
  headers: Headers;
};

export type deleteOAuthClientResponse = (deleteOAuthClientResponseSuccess | deleteOAuthClientResponseError)

export const getDeleteOAuthClientUrl = (clientId: string,) => {


  

  return `/oauth/clients/${clientId}`
}

export const deleteOAuthClient = async (clientId: string, options?: RequestInit): Promise<deleteOAuthClientResponse> => {
  
  return customInstance<deleteOAuthClientResponse>(getDeleteOAuthClientUrl(clientId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteOAuthClientMutationOptions = <TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOAuthClient>>, TError,{clientId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteOAuthClient>>, TError,{clientId: string}, TContext> => {

const mutationKey = ['deleteOAuthClient'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOAuthClient>>, {clientId: string}> = (props) => {
          const {clientId} = props ?? {};

          return  deleteOAuthClient(clientId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOAuthClientMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOAuthClient>>>
    
    export type DeleteOAuthClientMutationError = ErrorType<NotFoundResponse | InternalServerErrorResponse>

    /**
 * @summary Delete OAuth client
 */
export const useDeleteOAuthClient = <TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOAuthClient>>, TError,{clientId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteOAuthClient>>,
        TError,
        {clientId: string},
        TContext
      > => {
      return useMutation(getDeleteOAuthClientMutationOptions(options), queryClient);
    }
    /**
 * @summary Rotate OAuth client secret
 */
export type rotateOAuthClientSecretResponse200 = {
  data: RotateSecretResponse
  status: 200
}

export type rotateOAuthClientSecretResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type rotateOAuthClientSecretResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type rotateOAuthClientSecretResponseSuccess = (rotateOAuthClientSecretResponse200) & {
  headers: Headers;
};
export type rotateOAuthClientSecretResponseError = (rotateOAuthClientSecretResponse404 | rotateOAuthClientSecretResponse500) & {
  headers: Headers;
};

export type rotateOAuthClientSecretResponse = (rotateOAuthClientSecretResponseSuccess | rotateOAuthClientSecretResponseError)

export const getRotateOAuthClientSecretUrl = (clientId: string,) => {


  

  return `/oauth/clients/${clientId}/secret`
}

export const rotateOAuthClientSecret = async (clientId: string, options?: RequestInit): Promise<rotateOAuthClientSecretResponse> => {
  
  return customInstance<rotateOAuthClientSecretResponse>(getRotateOAuthClientSecretUrl(clientId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getRotateOAuthClientSecretMutationOptions = <TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rotateOAuthClientSecret>>, TError,{clientId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof rotateOAuthClientSecret>>, TError,{clientId: string}, TContext> => {

const mutationKey = ['rotateOAuthClientSecret'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rotateOAuthClientSecret>>, {clientId: string}> = (props) => {
          const {clientId} = props ?? {};

          return  rotateOAuthClientSecret(clientId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RotateOAuthClientSecretMutationResult = NonNullable<Awaited<ReturnType<typeof rotateOAuthClientSecret>>>
    
    export type RotateOAuthClientSecretMutationError = ErrorType<NotFoundResponse | InternalServerErrorResponse>

    /**
 * @summary Rotate OAuth client secret
 */
export const useRotateOAuthClientSecret = <TError = ErrorType<NotFoundResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rotateOAuthClientSecret>>, TError,{clientId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rotateOAuthClientSecret>>,
        TError,
        {clientId: string},
        TContext
      > => {
      return useMutation(getRotateOAuthClientSecretMutationOptions(options), queryClient);
    }
    