#!/bin/sh
set -e

# Validate Environment Variables
if [ -z "$VAULT_ADDR" ] || [ -z "$VAULT_FILE" ] || [ -z "VAULT_HOST_PATH" ]; then
    echo "[ERROR] VAULT_ADDR or VAULT_FILE or VAULT_HOST_PATH not set. Exiting."
    exit 1
fi

# Set default host address if not provided
HOST_ADDR=${VAULT_HOST_ADDR:-http://127.0.0.1:8200}

KEYS_FILE="$VAULT_FILE/keys.json"
ENV_OUTPUT_FILE="$VAULT_FILE/vault.env"

echo "[INIT] Internal Vault Address: $VAULT_ADDR"
echo "[INIT] External Host Address: $HOST_ADDR"

# ---------------------------------------------------------
# 1. Health Check (CORREGIDO: Usamos curl para evitar deadlock)
# ---------------------------------------------------------
echo "[INIT] Waiting for Vault to respond..."

# Intentamos conectar hasta 30 veces (1 minuto max)
MAX_RETRIES=30
COUNT=0

# Usamos curl -s (silent) pero comprobamos si conecta.
# Cualquier respuesta HTTP (incluso 501 o 503) es éxito de conexión.
while ! curl -s "$VAULT_ADDR/v1/sys/health" > /dev/null; do
    COUNT=$((COUNT+1))
    if [ "$COUNT" -ge "$MAX_RETRIES" ]; then
        echo "❌ [ERROR] Timeout waiting for Vault at $VAULT_ADDR"
        echo "           Ensure the service names in docker-compose match."
        exit 1
    fi
    sleep 2
done
echo "[INIT] Vault is reachable."

# ---------------------------------------------------------
# 2. Initialization
# ---------------------------------------------------------
if [ ! -f "$KEYS_FILE" ]; then
   echo "[INFO] Initializing Vault..."
   vault operator init -key-shares=1 -key-threshold=1 -format=json > "$KEYS_FILE"
   echo "[INFO] Initialization complete."
else
   echo "[INFO] Keys file found. Skipping initialization."
fi

# ---------------------------------------------------------
# 3. Unseal
# ---------------------------------------------------------
SEALED_STATUS=$(vault status -format=json | jq -r ".sealed")

if [ "$SEALED_STATUS" = "true" ]; then
    echo "[INFO] Unsealing Vault..."
    UNSEAL_KEY=$(jq -r ".unseal_keys_b64[0]" "$KEYS_FILE")

    if [ -z "$UNSEAL_KEY" ] || [ "$UNSEAL_KEY" = "null" ]; then
        echo "[ERROR] Could not retrieve unseal key from $KEYS_FILE."
        exit 1
    fi

    # Unseal y silenciar salida si es exitoso
    vault operator unseal "$UNSEAL_KEY" > /dev/null
    echo "[INFO] Vault unsealed successfully."
else
    echo "[INFO] Vault is already unsealed."
fi

# ---------------------------------------------------------
# 4. Generate Host Environment File
# ---------------------------------------------------------
echo "[INFO] Generating .env file..."
ROOT_TOKEN=$(jq -r ".root_token" "$KEYS_FILE")

cat <<EOF > "$ENV_OUTPUT_FILE"
# Generated by Vault Auto-Init
VAULT_ADDR=$HOST_ADDR
VAULT_TOKEN=$ROOT_TOKEN
VAULT_SKIP_VERIFY=true
VAULT_MOUNT=rainbow
VAULT_PATH=$VAULT_HOST_PATH
VAULT_APP_DB=database/postgres
VAULT_APP_WALLET=wallet/main
VAULT_APP_PRIV_KEY=crypto/keys/private
VAULT_APP_PUB_PKEY=crypto/keys/public
VAULT_APP_CERT=crypto/certificates/main
EOF

echo "[SUCCESS] Environment file generated at: $ENV_OUTPUT_FILE"