#!/bin/sh
set -e

# Validate required variables
if [ -z "$VAULT_ADDR" ] || [ -z "$VAULT_FILE" ]; then
    echo "[ERROR] VAULT_ADDR or VAULT_FILE not set. Exiting."
    exit 1
fi

KEYS_FILE="$VAULT_FILE/keys.json"
ENV_OUTPUT_FILE="$VAULT_FILE/vault.env"

# 1. Health Check
while ! vault status > /dev/null 2>&1; do
    sleep 1
done

# 2. Initialization
if [ ! -f "$KEYS_FILE" ]; then
   echo "[INFO] Initializing Vault..."
   vault operator init -key-shares=1 -key-threshold=1 -format=json > "$KEYS_FILE"
fi

# 3. Unseal
SEALED_STATUS=$(vault status -format=json | jq -r ".sealed")

if [ "$SEALED_STATUS" = "true" ]; then
    echo "[INFO] Unsealing Vault..."
    UNSEAL_KEY=$(jq -r ".unseal_keys_b64[0]" "$KEYS_FILE")

    if [ -z "$UNSEAL_KEY" ] || [ "$UNSEAL_KEY" = "null" ]; then
        echo "[ERROR] Could not retrieve unseal key."
        exit 1
    fi
    vault operator unseal "$UNSEAL_KEY" > /dev/null
fi

# 4. Generate Host Environment File
echo "[INFO] Generating .env file..."
ROOT_TOKEN=$(jq -r ".root_token" "$KEYS_FILE")

cat <<EOF > "$ENV_OUTPUT_FILE"
# Generated by Vault Auto-Init
VAULT_ADDR=http://127.0.0.1:8202
VAULT_TOKEN=$ROOT_TOKEN
VAULT_SKIP_VERIFY=true
VAULT_MOUNT=rainbow
VAULT_APP_DB=database/postgres
VAULT_APP_WALLET=wallet/main
VAULT_APP_PRIV_KEY=crypto/keys/private
VAULT_APP_PUB_PKEY=crypto/keys/public
VAULT_APP_CERT=crypto/certificates/main
EOF