/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Rainbow Frontend Gateway API
 * OpenAPI specification for the Rainbow Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */
import type { CatalogExtraFields } from './catalogExtraFields';
import type { CatalogMinimized } from './catalogMinimized';
import type { DataService } from './dataService';
import type { DataServiceMinimized } from './dataServiceMinimized';
import type { Dataset } from './dataset';
import type { DatasetMinimized } from './datasetMinimized';
import type { OdrlOffer } from './odrlOffer';

export interface Catalog {
  '@context'?: string | string[];
  '@type'?: string;
  '@id'?: string;
  homepage?: string;
  theme?: string;
  keyword?: string;
  conformsTo?: string;
  creator?: string;
  identifier?: string;
  issued?: string;
  modified?: string;
  title?: string;
  description?: string[];
  participantId?: string;
  hasPolicy?: OdrlOffer[];
  extraFields?: CatalogExtraFields;
  catalog?: Catalog[] | CatalogMinimized[];
  dataset?: Dataset[] | DatasetMinimized[];
  service?: DataService | DataServiceMinimized | DataService[];
}
