/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * OpenAPI specification for the Eunomia DS-Agent Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */
import type { EventSubscriptionHeaders } from './eventSubscriptionHeaders';

export interface EventSubscription {
  id: string;
  callback_address: string;
  topic_pattern: string;
  secret?: string | null;
  headers?: EventSubscriptionHeaders;
  retry_limit?: number | null;
  active: boolean;
  created_at: string;
  updated_at?: string | null;
  expiration_time?: string | null;
}
