/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Rainbow Frontend Gateway API
 * OpenAPI specification for the Rainbow Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */
import type { NewOdrlPolicyDtoEntityType } from './newOdrlPolicyDtoEntityType';
import type { NewOdrlPolicyDtoInstantiationParameters } from './newOdrlPolicyDtoInstantiationParameters';
import type { OdrlPolicyInfo } from './odrlPolicyInfo';

export interface NewOdrlPolicyDto {
  id?: string;
  odrlOffer: OdrlPolicyInfo;
  entityId: string;
  entityType: NewOdrlPolicyDtoEntityType;
  sourceTemplateId?: string;
  sourceTemplateVersion?: string;
  instantiationParameters?: NewOdrlPolicyDtoInstantiationParameters;
}
