/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Rainbow Frontend Gateway API
 * OpenAPI specification for the Rainbow Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */
import type { NewTransferProcessDtoIdentifiers } from './newTransferProcessDtoIdentifiers';
import type { NewTransferProcessDtoProperties } from './newTransferProcessDtoProperties';

export interface NewTransferProcessDto {
  /** @nullable */
  id?: string | null;
  state: string;
  /** @nullable */
  stateAttribute?: string | null;
  associatedAgentPeer: string;
  protocol: string;
  transferDirection: string;
  agreementId: string;
  /** @nullable */
  callbackAddress?: string | null;
  role: string;
  /** @nullable */
  properties?: NewTransferProcessDtoProperties;
  /** @nullable */
  identifiers?: NewTransferProcessDtoIdentifiers;
}
