/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Rainbow Frontend Gateway API
 * OpenAPI specification for the Rainbow Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */
import type { ParameterDefinitionAutoFilledType } from './parameterDefinitionAutoFilledType';
import type { ParameterDefinitionParamType } from './parameterDefinitionParamType';

export interface ParameterDefinition {
  name: string;
  title: string;
  description?: string;
  paramType: ParameterDefinitionParamType;
  required: boolean;
  defaultValue?: string;
  autoFilled?: boolean;
  autoFilledType?: ParameterDefinitionAutoFilledType;
}
