/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ContractNegotiationRouteImport } from './routes/contract-negotiation/route'
import { Route as CatalogRouteImport } from './routes/catalog/route'
import { Route as IndexImport } from './routes/index'
import { Route as ContractNegotiationIndexImport } from './routes/contract-negotiation/index'
import { Route as CatalogIndexImport } from './routes/catalog/index'
import { Route as ContractNegotiationCnProcessRouteImport } from './routes/contract-negotiation/$cnProcess/route'
import { Route as CatalogCatalogIdRouteImport } from './routes/catalog/$catalogId/route'
import { Route as ContractNegotiationCnProcessIndexImport } from './routes/contract-negotiation/$cnProcess/index'
import { Route as CatalogCatalogIdIndexImport } from './routes/catalog/$catalogId/index'
import { Route as ContractNegotiationCnProcessMessageMessageIdImport } from './routes/contract-negotiation/$cnProcess/message.$messageId'
import { Route as CatalogCatalogIdDatasetDatasetIdImport } from './routes/catalog/$catalogId/dataset.$datasetId'
import { Route as CatalogCatalogIdDataServiceDataServiceIdImport } from './routes/catalog/$catalogId/data-service.$dataServiceId'

// Create/Update Routes

const ContractNegotiationRouteRoute = ContractNegotiationRouteImport.update({
  id: '/contract-negotiation',
  path: '/contract-negotiation',
  getParentRoute: () => rootRoute,
} as any)

const CatalogRouteRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContractNegotiationIndexRoute = ContractNegotiationIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContractNegotiationRouteRoute,
} as any)

const CatalogIndexRoute = CatalogIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRouteRoute,
} as any)

const ContractNegotiationCnProcessRouteRoute =
  ContractNegotiationCnProcessRouteImport.update({
    id: '/$cnProcess',
    path: '/$cnProcess',
    getParentRoute: () => ContractNegotiationRouteRoute,
  } as any)

const CatalogCatalogIdRouteRoute = CatalogCatalogIdRouteImport.update({
  id: '/$catalogId',
  path: '/$catalogId',
  getParentRoute: () => CatalogRouteRoute,
} as any)

const ContractNegotiationCnProcessIndexRoute =
  ContractNegotiationCnProcessIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ContractNegotiationCnProcessRouteRoute,
  } as any)

const CatalogCatalogIdIndexRoute = CatalogCatalogIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogCatalogIdRouteRoute,
} as any)

const ContractNegotiationCnProcessMessageMessageIdRoute =
  ContractNegotiationCnProcessMessageMessageIdImport.update({
    id: '/message/$messageId',
    path: '/message/$messageId',
    getParentRoute: () => ContractNegotiationCnProcessRouteRoute,
  } as any)

const CatalogCatalogIdDatasetDatasetIdRoute =
  CatalogCatalogIdDatasetDatasetIdImport.update({
    id: '/dataset/$datasetId',
    path: '/dataset/$datasetId',
    getParentRoute: () => CatalogCatalogIdRouteRoute,
  } as any)

const CatalogCatalogIdDataServiceDataServiceIdRoute =
  CatalogCatalogIdDataServiceDataServiceIdImport.update({
    id: '/data-service/$dataServiceId',
    path: '/data-service/$dataServiceId',
    getParentRoute: () => CatalogCatalogIdRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRoute
    }
    '/contract-negotiation': {
      id: '/contract-negotiation'
      path: '/contract-negotiation'
      fullPath: '/contract-negotiation'
      preLoaderRoute: typeof ContractNegotiationRouteImport
      parentRoute: typeof rootRoute
    }
    '/catalog/$catalogId': {
      id: '/catalog/$catalogId'
      path: '/$catalogId'
      fullPath: '/catalog/$catalogId'
      preLoaderRoute: typeof CatalogCatalogIdRouteImport
      parentRoute: typeof CatalogRouteImport
    }
    '/contract-negotiation/$cnProcess': {
      id: '/contract-negotiation/$cnProcess'
      path: '/$cnProcess'
      fullPath: '/contract-negotiation/$cnProcess'
      preLoaderRoute: typeof ContractNegotiationCnProcessRouteImport
      parentRoute: typeof ContractNegotiationRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexImport
      parentRoute: typeof CatalogRouteImport
    }
    '/contract-negotiation/': {
      id: '/contract-negotiation/'
      path: '/'
      fullPath: '/contract-negotiation/'
      preLoaderRoute: typeof ContractNegotiationIndexImport
      parentRoute: typeof ContractNegotiationRouteImport
    }
    '/catalog/$catalogId/': {
      id: '/catalog/$catalogId/'
      path: '/'
      fullPath: '/catalog/$catalogId/'
      preLoaderRoute: typeof CatalogCatalogIdIndexImport
      parentRoute: typeof CatalogCatalogIdRouteImport
    }
    '/contract-negotiation/$cnProcess/': {
      id: '/contract-negotiation/$cnProcess/'
      path: '/'
      fullPath: '/contract-negotiation/$cnProcess/'
      preLoaderRoute: typeof ContractNegotiationCnProcessIndexImport
      parentRoute: typeof ContractNegotiationCnProcessRouteImport
    }
    '/catalog/$catalogId/data-service/$dataServiceId': {
      id: '/catalog/$catalogId/data-service/$dataServiceId'
      path: '/data-service/$dataServiceId'
      fullPath: '/catalog/$catalogId/data-service/$dataServiceId'
      preLoaderRoute: typeof CatalogCatalogIdDataServiceDataServiceIdImport
      parentRoute: typeof CatalogCatalogIdRouteImport
    }
    '/catalog/$catalogId/dataset/$datasetId': {
      id: '/catalog/$catalogId/dataset/$datasetId'
      path: '/dataset/$datasetId'
      fullPath: '/catalog/$catalogId/dataset/$datasetId'
      preLoaderRoute: typeof CatalogCatalogIdDatasetDatasetIdImport
      parentRoute: typeof CatalogCatalogIdRouteImport
    }
    '/contract-negotiation/$cnProcess/message/$messageId': {
      id: '/contract-negotiation/$cnProcess/message/$messageId'
      path: '/message/$messageId'
      fullPath: '/contract-negotiation/$cnProcess/message/$messageId'
      preLoaderRoute: typeof ContractNegotiationCnProcessMessageMessageIdImport
      parentRoute: typeof ContractNegotiationCnProcessRouteImport
    }
  }
}

// Create and export the route tree

interface CatalogCatalogIdRouteRouteChildren {
  CatalogCatalogIdIndexRoute: typeof CatalogCatalogIdIndexRoute
  CatalogCatalogIdDataServiceDataServiceIdRoute: typeof CatalogCatalogIdDataServiceDataServiceIdRoute
  CatalogCatalogIdDatasetDatasetIdRoute: typeof CatalogCatalogIdDatasetDatasetIdRoute
}

const CatalogCatalogIdRouteRouteChildren: CatalogCatalogIdRouteRouteChildren = {
  CatalogCatalogIdIndexRoute: CatalogCatalogIdIndexRoute,
  CatalogCatalogIdDataServiceDataServiceIdRoute:
    CatalogCatalogIdDataServiceDataServiceIdRoute,
  CatalogCatalogIdDatasetDatasetIdRoute: CatalogCatalogIdDatasetDatasetIdRoute,
}

const CatalogCatalogIdRouteRouteWithChildren =
  CatalogCatalogIdRouteRoute._addFileChildren(
    CatalogCatalogIdRouteRouteChildren,
  )

interface CatalogRouteRouteChildren {
  CatalogCatalogIdRouteRoute: typeof CatalogCatalogIdRouteRouteWithChildren
  CatalogIndexRoute: typeof CatalogIndexRoute
}

const CatalogRouteRouteChildren: CatalogRouteRouteChildren = {
  CatalogCatalogIdRouteRoute: CatalogCatalogIdRouteRouteWithChildren,
  CatalogIndexRoute: CatalogIndexRoute,
}

const CatalogRouteRouteWithChildren = CatalogRouteRoute._addFileChildren(
  CatalogRouteRouteChildren,
)

interface ContractNegotiationCnProcessRouteRouteChildren {
  ContractNegotiationCnProcessIndexRoute: typeof ContractNegotiationCnProcessIndexRoute
  ContractNegotiationCnProcessMessageMessageIdRoute: typeof ContractNegotiationCnProcessMessageMessageIdRoute
}

const ContractNegotiationCnProcessRouteRouteChildren: ContractNegotiationCnProcessRouteRouteChildren =
  {
    ContractNegotiationCnProcessIndexRoute:
      ContractNegotiationCnProcessIndexRoute,
    ContractNegotiationCnProcessMessageMessageIdRoute:
      ContractNegotiationCnProcessMessageMessageIdRoute,
  }

const ContractNegotiationCnProcessRouteRouteWithChildren =
  ContractNegotiationCnProcessRouteRoute._addFileChildren(
    ContractNegotiationCnProcessRouteRouteChildren,
  )

interface ContractNegotiationRouteRouteChildren {
  ContractNegotiationCnProcessRouteRoute: typeof ContractNegotiationCnProcessRouteRouteWithChildren
  ContractNegotiationIndexRoute: typeof ContractNegotiationIndexRoute
}

const ContractNegotiationRouteRouteChildren: ContractNegotiationRouteRouteChildren =
  {
    ContractNegotiationCnProcessRouteRoute:
      ContractNegotiationCnProcessRouteRouteWithChildren,
    ContractNegotiationIndexRoute: ContractNegotiationIndexRoute,
  }

const ContractNegotiationRouteRouteWithChildren =
  ContractNegotiationRouteRoute._addFileChildren(
    ContractNegotiationRouteRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteRouteWithChildren
  '/contract-negotiation': typeof ContractNegotiationRouteRouteWithChildren
  '/catalog/$catalogId': typeof CatalogCatalogIdRouteRouteWithChildren
  '/contract-negotiation/$cnProcess': typeof ContractNegotiationCnProcessRouteRouteWithChildren
  '/catalog/': typeof CatalogIndexRoute
  '/contract-negotiation/': typeof ContractNegotiationIndexRoute
  '/catalog/$catalogId/': typeof CatalogCatalogIdIndexRoute
  '/contract-negotiation/$cnProcess/': typeof ContractNegotiationCnProcessIndexRoute
  '/catalog/$catalogId/data-service/$dataServiceId': typeof CatalogCatalogIdDataServiceDataServiceIdRoute
  '/catalog/$catalogId/dataset/$datasetId': typeof CatalogCatalogIdDatasetDatasetIdRoute
  '/contract-negotiation/$cnProcess/message/$messageId': typeof ContractNegotiationCnProcessMessageMessageIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/contract-negotiation': typeof ContractNegotiationIndexRoute
  '/catalog/$catalogId': typeof CatalogCatalogIdIndexRoute
  '/contract-negotiation/$cnProcess': typeof ContractNegotiationCnProcessIndexRoute
  '/catalog/$catalogId/data-service/$dataServiceId': typeof CatalogCatalogIdDataServiceDataServiceIdRoute
  '/catalog/$catalogId/dataset/$datasetId': typeof CatalogCatalogIdDatasetDatasetIdRoute
  '/contract-negotiation/$cnProcess/message/$messageId': typeof ContractNegotiationCnProcessMessageMessageIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteRouteWithChildren
  '/contract-negotiation': typeof ContractNegotiationRouteRouteWithChildren
  '/catalog/$catalogId': typeof CatalogCatalogIdRouteRouteWithChildren
  '/contract-negotiation/$cnProcess': typeof ContractNegotiationCnProcessRouteRouteWithChildren
  '/catalog/': typeof CatalogIndexRoute
  '/contract-negotiation/': typeof ContractNegotiationIndexRoute
  '/catalog/$catalogId/': typeof CatalogCatalogIdIndexRoute
  '/contract-negotiation/$cnProcess/': typeof ContractNegotiationCnProcessIndexRoute
  '/catalog/$catalogId/data-service/$dataServiceId': typeof CatalogCatalogIdDataServiceDataServiceIdRoute
  '/catalog/$catalogId/dataset/$datasetId': typeof CatalogCatalogIdDatasetDatasetIdRoute
  '/contract-negotiation/$cnProcess/message/$messageId': typeof ContractNegotiationCnProcessMessageMessageIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/contract-negotiation'
    | '/catalog/$catalogId'
    | '/contract-negotiation/$cnProcess'
    | '/catalog/'
    | '/contract-negotiation/'
    | '/catalog/$catalogId/'
    | '/contract-negotiation/$cnProcess/'
    | '/catalog/$catalogId/data-service/$dataServiceId'
    | '/catalog/$catalogId/dataset/$datasetId'
    | '/contract-negotiation/$cnProcess/message/$messageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/contract-negotiation'
    | '/catalog/$catalogId'
    | '/contract-negotiation/$cnProcess'
    | '/catalog/$catalogId/data-service/$dataServiceId'
    | '/catalog/$catalogId/dataset/$datasetId'
    | '/contract-negotiation/$cnProcess/message/$messageId'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/contract-negotiation'
    | '/catalog/$catalogId'
    | '/contract-negotiation/$cnProcess'
    | '/catalog/'
    | '/contract-negotiation/'
    | '/catalog/$catalogId/'
    | '/contract-negotiation/$cnProcess/'
    | '/catalog/$catalogId/data-service/$dataServiceId'
    | '/catalog/$catalogId/dataset/$datasetId'
    | '/contract-negotiation/$cnProcess/message/$messageId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRouteRoute: typeof CatalogRouteRouteWithChildren
  ContractNegotiationRouteRoute: typeof ContractNegotiationRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRouteRoute: CatalogRouteRouteWithChildren,
  ContractNegotiationRouteRoute: ContractNegotiationRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/catalog",
        "/contract-negotiation"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/catalog": {
      "filePath": "catalog/route.tsx",
      "children": [
        "/catalog/$catalogId",
        "/catalog/"
      ]
    },
    "/contract-negotiation": {
      "filePath": "contract-negotiation/route.tsx",
      "children": [
        "/contract-negotiation/$cnProcess",
        "/contract-negotiation/"
      ]
    },
    "/catalog/$catalogId": {
      "filePath": "catalog/$catalogId/route.tsx",
      "parent": "/catalog",
      "children": [
        "/catalog/$catalogId/",
        "/catalog/$catalogId/data-service/$dataServiceId",
        "/catalog/$catalogId/dataset/$datasetId"
      ]
    },
    "/contract-negotiation/$cnProcess": {
      "filePath": "contract-negotiation/$cnProcess/route.tsx",
      "parent": "/contract-negotiation",
      "children": [
        "/contract-negotiation/$cnProcess/",
        "/contract-negotiation/$cnProcess/message/$messageId"
      ]
    },
    "/catalog/": {
      "filePath": "catalog/index.tsx",
      "parent": "/catalog"
    },
    "/contract-negotiation/": {
      "filePath": "contract-negotiation/index.tsx",
      "parent": "/contract-negotiation"
    },
    "/catalog/$catalogId/": {
      "filePath": "catalog/$catalogId/index.tsx",
      "parent": "/catalog/$catalogId"
    },
    "/contract-negotiation/$cnProcess/": {
      "filePath": "contract-negotiation/$cnProcess/index.tsx",
      "parent": "/contract-negotiation/$cnProcess"
    },
    "/catalog/$catalogId/data-service/$dataServiceId": {
      "filePath": "catalog/$catalogId/data-service.$dataServiceId.tsx",
      "parent": "/catalog/$catalogId"
    },
    "/catalog/$catalogId/dataset/$datasetId": {
      "filePath": "catalog/$catalogId/dataset.$datasetId.tsx",
      "parent": "/catalog/$catalogId"
    },
    "/contract-negotiation/$cnProcess/message/$messageId": {
      "filePath": "contract-negotiation/$cnProcess/message.$messageId.tsx",
      "parent": "/contract-negotiation/$cnProcess"
    }
  }
}
ROUTE_MANIFEST_END */
