/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Rainbow Frontend Gateway API
 * OpenAPI specification for the Rainbow Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorInfo,
  NewPolicyInstantiationDto,
  NewPolicyTemplateDto,
  OdrlPolicyDto,
  PolicyTemplateDto
} from '.././model';

import { customInstance } from '../../orval-mutator';
import type { ErrorType , BodyType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List policy templates
 */
export type getPolicyTemplatesResponse200 = {
  data: PolicyTemplateDto[]
  status: 200
}

export type getPolicyTemplatesResponse400 = {
  data: ErrorInfo
  status: 400
}

export type getPolicyTemplatesResponse401 = {
  data: ErrorInfo
  status: 401
}

export type getPolicyTemplatesResponse403 = {
  data: ErrorInfo
  status: 403
}

export type getPolicyTemplatesResponse404 = {
  data: ErrorInfo
  status: 404
}

export type getPolicyTemplatesResponse500 = {
  data: ErrorInfo
  status: 500
}
    
export type getPolicyTemplatesResponseSuccess = (getPolicyTemplatesResponse200) & {
  headers: Headers;
};
export type getPolicyTemplatesResponseError = (getPolicyTemplatesResponse400 | getPolicyTemplatesResponse401 | getPolicyTemplatesResponse403 | getPolicyTemplatesResponse404 | getPolicyTemplatesResponse500) & {
  headers: Headers;
};

export type getPolicyTemplatesResponse = (getPolicyTemplatesResponseSuccess | getPolicyTemplatesResponseError)

export const getGetPolicyTemplatesUrl = () => {


  

  return `/policy-templates`
}

export const getPolicyTemplates = async ( options?: RequestInit): Promise<getPolicyTemplatesResponse> => {
  
  return customInstance<getPolicyTemplatesResponse>(getGetPolicyTemplatesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPolicyTemplatesInfiniteQueryKey = () => {
    return [
    'infinite', `/policy-templates`
    ] as const;
    }

export const getGetPolicyTemplatesQueryKey = () => {
    return [
    `/policy-templates`
    ] as const;
    }

    
export const getGetPolicyTemplatesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getPolicyTemplates>>>, TError = ErrorType<ErrorInfo>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPolicyTemplatesInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPolicyTemplates>>> = ({ signal }) => getPolicyTemplates({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPolicyTemplatesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getPolicyTemplates>>>
export type GetPolicyTemplatesInfiniteQueryError = ErrorType<ErrorInfo>


export function useGetPolicyTemplatesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPolicyTemplates>>>, TError = ErrorType<ErrorInfo>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolicyTemplates>>,
          TError,
          Awaited<ReturnType<typeof getPolicyTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPolicyTemplatesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPolicyTemplates>>>, TError = ErrorType<ErrorInfo>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolicyTemplates>>,
          TError,
          Awaited<ReturnType<typeof getPolicyTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPolicyTemplatesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPolicyTemplates>>>, TError = ErrorType<ErrorInfo>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List policy templates
 */

export function useGetPolicyTemplatesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPolicyTemplates>>>, TError = ErrorType<ErrorInfo>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPolicyTemplatesInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetPolicyTemplatesQueryOptions = <TData = Awaited<ReturnType<typeof getPolicyTemplates>>, TError = ErrorType<ErrorInfo>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPolicyTemplatesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPolicyTemplates>>> = ({ signal }) => getPolicyTemplates({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPolicyTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof getPolicyTemplates>>>
export type GetPolicyTemplatesQueryError = ErrorType<ErrorInfo>


export function useGetPolicyTemplates<TData = Awaited<ReturnType<typeof getPolicyTemplates>>, TError = ErrorType<ErrorInfo>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolicyTemplates>>,
          TError,
          Awaited<ReturnType<typeof getPolicyTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPolicyTemplates<TData = Awaited<ReturnType<typeof getPolicyTemplates>>, TError = ErrorType<ErrorInfo>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolicyTemplates>>,
          TError,
          Awaited<ReturnType<typeof getPolicyTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPolicyTemplates<TData = Awaited<ReturnType<typeof getPolicyTemplates>>, TError = ErrorType<ErrorInfo>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List policy templates
 */

export function useGetPolicyTemplates<TData = Awaited<ReturnType<typeof getPolicyTemplates>>, TError = ErrorType<ErrorInfo>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPolicyTemplatesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a policy template
 */
export type createPolicyTemplateResponse201 = {
  data: PolicyTemplateDto
  status: 201
}

export type createPolicyTemplateResponse400 = {
  data: ErrorInfo
  status: 400
}

export type createPolicyTemplateResponse401 = {
  data: ErrorInfo
  status: 401
}

export type createPolicyTemplateResponse403 = {
  data: ErrorInfo
  status: 403
}

export type createPolicyTemplateResponse404 = {
  data: ErrorInfo
  status: 404
}

export type createPolicyTemplateResponse500 = {
  data: ErrorInfo
  status: 500
}
    
export type createPolicyTemplateResponseSuccess = (createPolicyTemplateResponse201) & {
  headers: Headers;
};
export type createPolicyTemplateResponseError = (createPolicyTemplateResponse400 | createPolicyTemplateResponse401 | createPolicyTemplateResponse403 | createPolicyTemplateResponse404 | createPolicyTemplateResponse500) & {
  headers: Headers;
};

export type createPolicyTemplateResponse = (createPolicyTemplateResponseSuccess | createPolicyTemplateResponseError)

export const getCreatePolicyTemplateUrl = () => {


  

  return `/policy-templates`
}

export const createPolicyTemplate = async (newPolicyTemplateDto: NewPolicyTemplateDto, options?: RequestInit): Promise<createPolicyTemplateResponse> => {
  
  return customInstance<createPolicyTemplateResponse>(getCreatePolicyTemplateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      newPolicyTemplateDto,)
  }
);}




export const getCreatePolicyTemplateMutationOptions = <TError = ErrorType<ErrorInfo>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPolicyTemplate>>, TError,{data: BodyType<NewPolicyTemplateDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createPolicyTemplate>>, TError,{data: BodyType<NewPolicyTemplateDto>}, TContext> => {

const mutationKey = ['createPolicyTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPolicyTemplate>>, {data: BodyType<NewPolicyTemplateDto>}> = (props) => {
          const {data} = props ?? {};

          return  createPolicyTemplate(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePolicyTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof createPolicyTemplate>>>
    export type CreatePolicyTemplateMutationBody = BodyType<NewPolicyTemplateDto>
    export type CreatePolicyTemplateMutationError = ErrorType<ErrorInfo>

    /**
 * @summary Create a policy template
 */
export const useCreatePolicyTemplate = <TError = ErrorType<ErrorInfo>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPolicyTemplate>>, TError,{data: BodyType<NewPolicyTemplateDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPolicyTemplate>>,
        TError,
        {data: BodyType<NewPolicyTemplateDto>},
        TContext
      > => {
      return useMutation(getCreatePolicyTemplateMutationOptions(options), queryClient);
    }
    /**
 * @summary Get all versions of a policy template
 */
export type getPolicyTemplateVersionsResponse200 = {
  data: PolicyTemplateDto[]
  status: 200
}

export type getPolicyTemplateVersionsResponse400 = {
  data: ErrorInfo
  status: 400
}

export type getPolicyTemplateVersionsResponse401 = {
  data: ErrorInfo
  status: 401
}

export type getPolicyTemplateVersionsResponse403 = {
  data: ErrorInfo
  status: 403
}

export type getPolicyTemplateVersionsResponse404 = {
  data: ErrorInfo
  status: 404
}

export type getPolicyTemplateVersionsResponse500 = {
  data: ErrorInfo
  status: 500
}
    
export type getPolicyTemplateVersionsResponseSuccess = (getPolicyTemplateVersionsResponse200) & {
  headers: Headers;
};
export type getPolicyTemplateVersionsResponseError = (getPolicyTemplateVersionsResponse400 | getPolicyTemplateVersionsResponse401 | getPolicyTemplateVersionsResponse403 | getPolicyTemplateVersionsResponse404 | getPolicyTemplateVersionsResponse500) & {
  headers: Headers;
};

export type getPolicyTemplateVersionsResponse = (getPolicyTemplateVersionsResponseSuccess | getPolicyTemplateVersionsResponseError)

export const getGetPolicyTemplateVersionsUrl = (id: string,) => {


  

  return `/policy-templates/${id}`
}

export const getPolicyTemplateVersions = async (id: string, options?: RequestInit): Promise<getPolicyTemplateVersionsResponse> => {
  
  return customInstance<getPolicyTemplateVersionsResponse>(getGetPolicyTemplateVersionsUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPolicyTemplateVersionsInfiniteQueryKey = (id: string,) => {
    return [
    'infinite', `/policy-templates/${id}`
    ] as const;
    }

export const getGetPolicyTemplateVersionsQueryKey = (id: string,) => {
    return [
    `/policy-templates/${id}`
    ] as const;
    }

    
export const getGetPolicyTemplateVersionsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getPolicyTemplateVersions>>>, TError = ErrorType<ErrorInfo>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPolicyTemplateVersionsInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPolicyTemplateVersions>>> = ({ signal }) => getPolicyTemplateVersions(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id),  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPolicyTemplateVersionsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getPolicyTemplateVersions>>>
export type GetPolicyTemplateVersionsInfiniteQueryError = ErrorType<ErrorInfo>


export function useGetPolicyTemplateVersionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPolicyTemplateVersions>>>, TError = ErrorType<ErrorInfo>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolicyTemplateVersions>>,
          TError,
          Awaited<ReturnType<typeof getPolicyTemplateVersions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPolicyTemplateVersionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPolicyTemplateVersions>>>, TError = ErrorType<ErrorInfo>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolicyTemplateVersions>>,
          TError,
          Awaited<ReturnType<typeof getPolicyTemplateVersions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPolicyTemplateVersionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPolicyTemplateVersions>>>, TError = ErrorType<ErrorInfo>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get all versions of a policy template
 */

export function useGetPolicyTemplateVersionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPolicyTemplateVersions>>>, TError = ErrorType<ErrorInfo>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPolicyTemplateVersionsInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetPolicyTemplateVersionsQueryOptions = <TData = Awaited<ReturnType<typeof getPolicyTemplateVersions>>, TError = ErrorType<ErrorInfo>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPolicyTemplateVersionsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPolicyTemplateVersions>>> = ({ signal }) => getPolicyTemplateVersions(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPolicyTemplateVersionsQueryResult = NonNullable<Awaited<ReturnType<typeof getPolicyTemplateVersions>>>
export type GetPolicyTemplateVersionsQueryError = ErrorType<ErrorInfo>


export function useGetPolicyTemplateVersions<TData = Awaited<ReturnType<typeof getPolicyTemplateVersions>>, TError = ErrorType<ErrorInfo>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolicyTemplateVersions>>,
          TError,
          Awaited<ReturnType<typeof getPolicyTemplateVersions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPolicyTemplateVersions<TData = Awaited<ReturnType<typeof getPolicyTemplateVersions>>, TError = ErrorType<ErrorInfo>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolicyTemplateVersions>>,
          TError,
          Awaited<ReturnType<typeof getPolicyTemplateVersions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPolicyTemplateVersions<TData = Awaited<ReturnType<typeof getPolicyTemplateVersions>>, TError = ErrorType<ErrorInfo>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get all versions of a policy template
 */

export function useGetPolicyTemplateVersions<TData = Awaited<ReturnType<typeof getPolicyTemplateVersions>>, TError = ErrorType<ErrorInfo>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPolicyTemplateVersionsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get a specific version of a policy template
 */
export type getPolicyTemplateVersionResponse200 = {
  data: PolicyTemplateDto
  status: 200
}

export type getPolicyTemplateVersionResponse400 = {
  data: ErrorInfo
  status: 400
}

export type getPolicyTemplateVersionResponse401 = {
  data: ErrorInfo
  status: 401
}

export type getPolicyTemplateVersionResponse403 = {
  data: ErrorInfo
  status: 403
}

export type getPolicyTemplateVersionResponse404 = {
  data: ErrorInfo
  status: 404
}

export type getPolicyTemplateVersionResponse500 = {
  data: ErrorInfo
  status: 500
}
    
export type getPolicyTemplateVersionResponseSuccess = (getPolicyTemplateVersionResponse200) & {
  headers: Headers;
};
export type getPolicyTemplateVersionResponseError = (getPolicyTemplateVersionResponse400 | getPolicyTemplateVersionResponse401 | getPolicyTemplateVersionResponse403 | getPolicyTemplateVersionResponse404 | getPolicyTemplateVersionResponse500) & {
  headers: Headers;
};

export type getPolicyTemplateVersionResponse = (getPolicyTemplateVersionResponseSuccess | getPolicyTemplateVersionResponseError)

export const getGetPolicyTemplateVersionUrl = (id: string,
    version: string,) => {


  

  return `/policy-templates/${id}/${version}`
}

export const getPolicyTemplateVersion = async (id: string,
    version: string, options?: RequestInit): Promise<getPolicyTemplateVersionResponse> => {
  
  return customInstance<getPolicyTemplateVersionResponse>(getGetPolicyTemplateVersionUrl(id,version),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPolicyTemplateVersionInfiniteQueryKey = (id: string,
    version: string,) => {
    return [
    'infinite', `/policy-templates/${id}/${version}`
    ] as const;
    }

export const getGetPolicyTemplateVersionQueryKey = (id: string,
    version: string,) => {
    return [
    `/policy-templates/${id}/${version}`
    ] as const;
    }

    
export const getGetPolicyTemplateVersionInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getPolicyTemplateVersion>>>, TError = ErrorType<ErrorInfo>>(id: string,
    version: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersion>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPolicyTemplateVersionInfiniteQueryKey(id,version);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPolicyTemplateVersion>>> = ({ signal }) => getPolicyTemplateVersion(id,version, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id && version),  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersion>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPolicyTemplateVersionInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getPolicyTemplateVersion>>>
export type GetPolicyTemplateVersionInfiniteQueryError = ErrorType<ErrorInfo>


export function useGetPolicyTemplateVersionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPolicyTemplateVersion>>>, TError = ErrorType<ErrorInfo>>(
 id: string,
    version: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersion>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolicyTemplateVersion>>,
          TError,
          Awaited<ReturnType<typeof getPolicyTemplateVersion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPolicyTemplateVersionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPolicyTemplateVersion>>>, TError = ErrorType<ErrorInfo>>(
 id: string,
    version: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersion>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolicyTemplateVersion>>,
          TError,
          Awaited<ReturnType<typeof getPolicyTemplateVersion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPolicyTemplateVersionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPolicyTemplateVersion>>>, TError = ErrorType<ErrorInfo>>(
 id: string,
    version: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersion>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get a specific version of a policy template
 */

export function useGetPolicyTemplateVersionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPolicyTemplateVersion>>>, TError = ErrorType<ErrorInfo>>(
 id: string,
    version: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersion>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPolicyTemplateVersionInfiniteQueryOptions(id,version,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetPolicyTemplateVersionQueryOptions = <TData = Awaited<ReturnType<typeof getPolicyTemplateVersion>>, TError = ErrorType<ErrorInfo>>(id: string,
    version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersion>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPolicyTemplateVersionQueryKey(id,version);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPolicyTemplateVersion>>> = ({ signal }) => getPolicyTemplateVersion(id,version, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id && version),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersion>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPolicyTemplateVersionQueryResult = NonNullable<Awaited<ReturnType<typeof getPolicyTemplateVersion>>>
export type GetPolicyTemplateVersionQueryError = ErrorType<ErrorInfo>


export function useGetPolicyTemplateVersion<TData = Awaited<ReturnType<typeof getPolicyTemplateVersion>>, TError = ErrorType<ErrorInfo>>(
 id: string,
    version: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersion>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolicyTemplateVersion>>,
          TError,
          Awaited<ReturnType<typeof getPolicyTemplateVersion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPolicyTemplateVersion<TData = Awaited<ReturnType<typeof getPolicyTemplateVersion>>, TError = ErrorType<ErrorInfo>>(
 id: string,
    version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersion>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolicyTemplateVersion>>,
          TError,
          Awaited<ReturnType<typeof getPolicyTemplateVersion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPolicyTemplateVersion<TData = Awaited<ReturnType<typeof getPolicyTemplateVersion>>, TError = ErrorType<ErrorInfo>>(
 id: string,
    version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersion>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get a specific version of a policy template
 */

export function useGetPolicyTemplateVersion<TData = Awaited<ReturnType<typeof getPolicyTemplateVersion>>, TError = ErrorType<ErrorInfo>>(
 id: string,
    version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPolicyTemplateVersion>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPolicyTemplateVersionQueryOptions(id,version,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Delete a specific version of a policy template
 */
export type deletePolicyTemplateVersionResponse204 = {
  data: void
  status: 204
}

export type deletePolicyTemplateVersionResponse400 = {
  data: ErrorInfo
  status: 400
}

export type deletePolicyTemplateVersionResponse401 = {
  data: ErrorInfo
  status: 401
}

export type deletePolicyTemplateVersionResponse403 = {
  data: ErrorInfo
  status: 403
}

export type deletePolicyTemplateVersionResponse404 = {
  data: ErrorInfo
  status: 404
}

export type deletePolicyTemplateVersionResponse500 = {
  data: ErrorInfo
  status: 500
}
    
export type deletePolicyTemplateVersionResponseSuccess = (deletePolicyTemplateVersionResponse204) & {
  headers: Headers;
};
export type deletePolicyTemplateVersionResponseError = (deletePolicyTemplateVersionResponse400 | deletePolicyTemplateVersionResponse401 | deletePolicyTemplateVersionResponse403 | deletePolicyTemplateVersionResponse404 | deletePolicyTemplateVersionResponse500) & {
  headers: Headers;
};

export type deletePolicyTemplateVersionResponse = (deletePolicyTemplateVersionResponseSuccess | deletePolicyTemplateVersionResponseError)

export const getDeletePolicyTemplateVersionUrl = (id: string,
    version: string,) => {


  

  return `/policy-templates/${id}/${version}`
}

export const deletePolicyTemplateVersion = async (id: string,
    version: string, options?: RequestInit): Promise<deletePolicyTemplateVersionResponse> => {
  
  return customInstance<deletePolicyTemplateVersionResponse>(getDeletePolicyTemplateVersionUrl(id,version),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeletePolicyTemplateVersionMutationOptions = <TError = ErrorType<ErrorInfo>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePolicyTemplateVersion>>, TError,{id: string;version: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePolicyTemplateVersion>>, TError,{id: string;version: string}, TContext> => {

const mutationKey = ['deletePolicyTemplateVersion'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePolicyTemplateVersion>>, {id: string;version: string}> = (props) => {
          const {id,version} = props ?? {};

          return  deletePolicyTemplateVersion(id,version,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePolicyTemplateVersionMutationResult = NonNullable<Awaited<ReturnType<typeof deletePolicyTemplateVersion>>>
    
    export type DeletePolicyTemplateVersionMutationError = ErrorType<ErrorInfo>

    /**
 * @summary Delete a specific version of a policy template
 */
export const useDeletePolicyTemplateVersion = <TError = ErrorType<ErrorInfo>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePolicyTemplateVersion>>, TError,{id: string;version: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePolicyTemplateVersion>>,
        TError,
        {id: string;version: string},
        TContext
      > => {
      return useMutation(getDeletePolicyTemplateVersionMutationOptions(options), queryClient);
    }
    /**
 * @summary Instantiate an ODRL offer from a template
 */
export type instantiateOdrlOfferResponse201 = {
  data: OdrlPolicyDto
  status: 201
}

export type instantiateOdrlOfferResponse400 = {
  data: ErrorInfo
  status: 400
}

export type instantiateOdrlOfferResponse401 = {
  data: ErrorInfo
  status: 401
}

export type instantiateOdrlOfferResponse403 = {
  data: ErrorInfo
  status: 403
}

export type instantiateOdrlOfferResponse404 = {
  data: ErrorInfo
  status: 404
}

export type instantiateOdrlOfferResponse500 = {
  data: ErrorInfo
  status: 500
}
    
export type instantiateOdrlOfferResponseSuccess = (instantiateOdrlOfferResponse201) & {
  headers: Headers;
};
export type instantiateOdrlOfferResponseError = (instantiateOdrlOfferResponse400 | instantiateOdrlOfferResponse401 | instantiateOdrlOfferResponse403 | instantiateOdrlOfferResponse404 | instantiateOdrlOfferResponse500) & {
  headers: Headers;
};

export type instantiateOdrlOfferResponse = (instantiateOdrlOfferResponseSuccess | instantiateOdrlOfferResponseError)

export const getInstantiateOdrlOfferUrl = () => {


  

  return `/policy-templates/instantiate-odrl-offer`
}

export const instantiateOdrlOffer = async (newPolicyInstantiationDto: NewPolicyInstantiationDto, options?: RequestInit): Promise<instantiateOdrlOfferResponse> => {
  
  return customInstance<instantiateOdrlOfferResponse>(getInstantiateOdrlOfferUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      newPolicyInstantiationDto,)
  }
);}




export const getInstantiateOdrlOfferMutationOptions = <TError = ErrorType<ErrorInfo>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof instantiateOdrlOffer>>, TError,{data: BodyType<NewPolicyInstantiationDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof instantiateOdrlOffer>>, TError,{data: BodyType<NewPolicyInstantiationDto>}, TContext> => {

const mutationKey = ['instantiateOdrlOffer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof instantiateOdrlOffer>>, {data: BodyType<NewPolicyInstantiationDto>}> = (props) => {
          const {data} = props ?? {};

          return  instantiateOdrlOffer(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type InstantiateOdrlOfferMutationResult = NonNullable<Awaited<ReturnType<typeof instantiateOdrlOffer>>>
    export type InstantiateOdrlOfferMutationBody = BodyType<NewPolicyInstantiationDto>
    export type InstantiateOdrlOfferMutationError = ErrorType<ErrorInfo>

    /**
 * @summary Instantiate an ODRL offer from a template
 */
export const useInstantiateOdrlOffer = <TError = ErrorType<ErrorInfo>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof instantiateOdrlOffer>>, TError,{data: BodyType<NewPolicyInstantiationDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof instantiateOdrlOffer>>,
        TError,
        {data: BodyType<NewPolicyInstantiationDto>},
        TContext
      > => {
      return useMutation(getInstantiateOdrlOfferMutationOptions(options), queryClient);
    }
    